### ISSUE TITLE
Convert regexes in grammar to strings

### ISSUE THREAD

**Issue by burodepeper** [burodepeper/language-markdown#10]
Hey @leipert,
How difficult would it be to add something to `/lib/main.coffee` when the grammar is loaded that converts any `match`, `begin` or `end` fields that are a _normal_ regex to one of those double escapes strings that the Grammar wants?

That would certainly make writing regexes a lot more pleasurable. Look at the difference:
![schermafbeelding 2015-09-11 om 09 05 25](https://cloud.githubusercontent.com/assets/3703530/9808955/5d1a9360-5864-11e5-912a-cd3f683cf55a.png)

**Comment by burodepeper** [comment]
Btw, I don't mind doing this myself, but you'd have to point me in the right direction. It's probably just another shackle that has to be added to your chain, but I'm not yet familiar with those.

**Comment by leipert** [comment]
That should be really easy. We just have to catalogue which entries contain regex (match/begin/end) etc and do a loop over it :+1:

I will implement it today.

**Comment by burodepeper** [comment]
That would be great!!

**Comment by burodepeper** [comment]
I'm closing this issue for now. Still hopeful to eventually implement it, but `CSON.readFileSync()` fails when a file contains a regular expression. So solving this has to find a way 'around' using `CSON`.
