### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

### ISSUE THREAD

**Issue by msnns** [burodepeper/language-markdown#110]
Happens when using the formatting syntaxes.

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [language-markdown](https://github.com/burodepeper/language-markdown) package, v0.13.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

```
At /Users/.../.atom/packages/language-markdown/lib/main.coffee:169

TypeError: Cannot read property 'getSelectedText' of undefined
    at Object.module.exports.emphasizeSelection (/Users/.../.atom/packages/language-markdown/lib/main.coffee:169:20)
    at atom-text-editor.subscriptions.add.atom.commands.add.markdown:strong-emphasis (/Users/.../.atom/packages/language-markdown/lib/main.coffee:51:102)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:15.4.0 core:move-right (input.hidden-input)
     -0:15.4.0 core:move-left (input.hidden-input)
     -0:15.3.0 core:move-right (input.hidden-input)
     -0:15.3.0 core:move-left (input.hidden-input)
     -0:11.3.0 core:move-right (input.hidden-input)
     -0:11.2.0 core:move-left (input.hidden-input)
     -0:11 core:move-right (input.hidden-input)
     -0:11 core:move-left (input.hidden-input)
     -0:10.9.0 core:move-right (input.hidden-input)
     -0:10.9.0 core:move-left (input.hidden-input)
     -0:10.8.0 core:move-right (input.hidden-input)
     -0:10.8.0 core:move-left (input.hidden-input)
 17x -0:10.3.0 core:backspace (input.hidden-input)
     -0:07.7.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:07.7.0 editor:newline (input.hidden-input)
  4x -0:03.0 markdown:strong-emphasis (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "stylus-autocompile",
      "language-gfm",
      "linter-gcc",
      "language-cpp14"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v3.0.0
atom-handlebars, v1.3.0
build-less, v0.1.1
language-haml, v0.24.0
language-haskell, v1.7.15
language-lua, v0.9.4
language-markdown, v0.13.0
language-swift, v0.4.0
linter, v1.11.4
linter-swiftc, v2.0.0
markdown-writer, v2.3.3

# Dev
No dev packages
```

**Comment by burodepeper** [comment]
Thanks for reporting. Does the issue persist after restarting Atom? If it does, could you supply instructions that consistently reproduce this issue? From the information above, I've been unable to do so.

**Comment by msnns** [comment]
Sorry for the delay.

Yes, merely typing `*` or `_` for emphasizing or bolding text produces this issue.  It happens regardless of whether I restart Atom.

**Comment by burodepeper** [comment]
Could you try disabling your other packages (except for `language-markdown` obviously), restart Atom, and see if the problem still persists?

I've got an idea on how to approach this from another angle, but I don't think I've got time to implement it until after this weekend. Are you familiar with `git` and/or running an atom-package in dev-mode to help sort this out?

**Comment by msnns** [comment]
I fixed the problem.  Just wrapped a `try..catch` around some code :P.

```coffee
try  # line 169
  text = editor.getSelectedText()
catch err
  event.abortKeyBinding()
  return  # line 173
```
Works just fine now.  No errors.

(I'm not sure if I need `event.abortKeyBinding()`; I'm not familiar with Atom's API.)

**Comment by burodepeper** [comment]
: ) Good that it works, too bad it's not a "true" solution. I'll patch it up your way and put out a new version soon. Are you interested in helping dig further down to the real problem? I've been falsely and naively assuming that getting the editor and position from the event was a given. I was already planning on putting some checks in, just in case. My experience thus far with Atom are that things can be a bit unpredictable, even in similar environments.

`event.abortKeyBinding()` releases the keyEvent by the way; (in this case pressing either the `_` or `*`). Basically, I'm capturing it before anything else, and if I've got no use for it, I'll abort it and it will do what it would have done anyway (in this case, probably insert that character, unless another package is also listening for it). If you don't abort a key-binding, it won't be passed down to the editor itself.

Thanks for your help so far!

**Comment by msnns** [comment]
I realized that I could've just checked for `editor` and `abortKeyBinding` inside of an `else`.

Yeah, I did dig deeper, and I found, when running the following code and checking the console's log...
```coffeescript
_getEditorAndPosition: (event) ->
  editor = event.target.model
  console.log 'Target: ' + event.target
  console.log 'Model: ' + event.target.model
  if editor
    position = editor.cursors[0].marker.oldHeadBufferPosition
    return {editor, position}
  else
    event.abortKeyBinding()
```
...`event.target` is an `HTMLInputElement`, and `target.model` is just _`undefined`_.

From this, I'm assuming it's something in the Atom editor causing this problem.

**Comment by burodepeper** [comment]
If I'm not mistaken, the `event.target || HTMLInputElement` is the hidden element in which you are editing/writing your code. The `event` is a custom event, and `event.target.model` I assumed would be a consistent representation of the `editor`. I've pieced this all together basically by going through the inspector and looking for the stuff that I needed, because I couldn't find any simple APIs in the official docs (at that time). Maybe things have changed.

**Comment by burodepeper** [comment]
I'm going to rework some stuff I think. See https://atom.io/docs/api/v1.7.3/Workspace#instance-getActiveTextEditor

**Comment by burodepeper** [comment]
Ran into #111 while working on this. I might need to rethink how all actions are dealt with when multiple cursors/selections are involved. I expected something like this to creep up one day, and apparently today is that day.
