### ISSUE TITLE
Fenced-code-blocks with unrecognized languages are not closed properly

### ISSUE THREAD

**Issue by heavywatal** [burodepeper/language-markdown#112]
(Backslashes are replaced with single-quotes for visualization here)
```md
'''r
# first block
'''

*dead, non-italic*
we are still in a `fenced.code.md`, `ctrl-cmd-p` says.

'''r
# second block
''' (here the first block seems to be closed)

*resurrection! italic*
```

The second problem is that R is not recognized as a language.

**Comment by burodepeper** [comment]
Thanks for reporting, replicated, and I'll have a look at it.

**Comment by burodepeper** [comment]
![schermafbeelding 2016-05-17 om 14 37 32](https://cloud.githubusercontent.com/assets/3703530/15322407/f6ecae1e-1c3c-11e6-9ee2-3b65ea8c889d.png)

**Comment by burodepeper** [comment]
I've re-added R to the list of supported fenced-code-blocks. It was previously removed in favor of the R Markdown syntax `'''{r engine='cpp'}` (replace single quotes with backticks), but there's no harm in putting it back in. In addition, and this might have been overlooked by myself, the closing line of the fenced-code-block doesn't allow any content after the backticks on the same line.

**Comment by burodepeper** [comment]
You can expect this to be in the next update (hopefully by the end of the week). Let me know after updating if you still run into issues.
