### ISSUE TITLE
Line Highlighting on Code Fences

### ISSUE THREAD

**Issue by eloquently** [burodepeper/language-markdown#114]
I like to add line highlights to my code fences using the syntax described [here](http://zpao.com/posts/adding-line-highlights-to-markdown-code-fences/).

This breaks the highlighter with language-markdown. I've solved it by replacing the code fence "begin" regex in `grammars/language-markdown.json`. e.g. for JavaScript:

```diff
         {
-         "begin": "^\\s*([`~]{3,})\\s*(\\{?)((?:\\.?)(?:javascript|js|jsx))(?=( |$))\\s*([^`\\}]*)(\\}?)$",
+         "begin": "^\\s*([`~]{3,})\\s*(\\{?)((?:\\.?)(?:javascript|js|jsx)(?:\\{[0-9,\\-\\s]*\\})?)(?=( |$))\\s*([^`\\}]*)(\\}?)$",
          "beginCaptures": {
            "1": {
              "name": "punctuation.md"
            },
            "2": {
              "name": "punctuation.md"
            },
            "3": {
              "name": "language.constant.md"
            },
            "5": {
              "patterns": [
                {
                  "include": "#special-attribute-elements"
                }
              ]
            },
            "6": {
              "name": "punctuation.md"
            }
          },
```

Is this the best way to handle this? If so, I can submit a PR with these regexes if you have any interest in supporting this line highlights syntax. It's not really part of any markdown standard, and I'm not sure how widespread this practice is, so I understand if it's more trouble than it's worth!

**Comment by burodepeper** [comment]
> It's not really part of any markdown standard, and I'm not sure how widespread this practice is

Still interesting though. I'll respond more in depth when I have a chance to take a better look at it. I'm not sure what the best syntax would be though. This grammar already includes the [special attributes](https://michelf.ca/projects/php-markdown/extra/#spe-attr) from Markdown Extra which is rather similar. The only difference in syntax is that a space after the language is required in the current grammar.

I like how R Markdown uses `key=value` pairs for fenced-code-blocks, see [page 2 on this pdf](http://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf). I think something similar to that would be a good middle ground.

cc @zpao: do you have any idea what the adoption rate of your concept is?

**Comment by zpao** [comment]
I've only heard of a couple people using the syntax. Mostly I just use it in the React tutorial, which was the reason I wrote that in the first place. Somebody wrote a similar addition on top of Marked (https://gist.github.com/namuol/8f3cd36a8d2f6ac8899d) but not sure it ever really went anywhere.

There's some related discussion in http://talk.commonmark.org/t/code-blocks-extension-for-filenames-and-line-numbers/536/4. Not about what I did but around adding more metadata to code blocks, similar to the special attributes you linked to. While I have some small attachment to what I did, I'd much rather move in the direction of something that's somewhat supported by parsers without having to manually hook into the parser. Markdown Extra is pretty widespread so seems like that might be the best thing to support.

**Comment by zpao** [comment]
If you wanted to support the evolving commonmark spec you could just ensure that anything (except backtick) is allowed in the "info string" and doesn't break highlighting of the rest of the document (based on http://spec.commonmark.org/0.25/#info-string)

**Comment by burodepeper** [comment]
@zpao Thanks for your input!

I think your last remark about allowing anything in the info-string is what I'm probably going for. I saw some interesting ideas about the `{key=value}` attribute syntax on talk.commonmark.org (wasn't aware of that, thanks) too.

**Comment by burodepeper** [comment]
@eloquently See the commit above. This fixes your issue, but I've chosen not to apply any scopes to the line-numbers per se. I think it's rather premature and as of yet unnecessary to make a decision in that area. I'm still working on a few other changes in the dev branch, but expect this change to be part of the next update to the package. I'm marking this as closed, because I think this solution is at least good enough.
