### ISSUE TITLE
Trailing whitespaces

### ISSUE THREAD

**Issue by kachkaev** [burodepeper/language-markdown#115]
Hi David,

I quite liked your package and decided to use it as a replacement for `language-gfm`. However, after a short while I noticed that the trailing spaced started to disappear on save. This is because of a default behaviour in Atom's [`workspace`](https://github.com/atom/whitespace) package. I tried to disable this by doing what they suggest in readme:

`config.cson`:

``` cson
"*":
  ...
  whitespace:
    ".text.md":
      removeTrailingWhitespace: false
```

Tried a few other ways of expressing my intention in the config, but none worked. Unfortunately, I had to give up and return to gfm, since restoring the whitespaces before every commit is a pain. Could you please update the docs or implement something to make it possible to keep the spaces before the newline characters?

I imagine this can be possible already. In this case the path to the solution is probably too complex or unclear.

**Comment by burodepeper** [comment]
I think the "error" is in your `config.cson`. The setting doesn't seem to work as part of the `*` scope, but it does (for me) in the `.md.text` scope. If you scroll quite far down in `config.cson` you'll find that particular key there, otherwise add it yourself. The correct config should then be (or at least, this is what works for me):

```cson
".md.text":
  whitespace:
    removeTrailingWhitespace: false
```

Make sure that there is no leading whitespace, otherwise you're in some other scope.

**Comment by kachkaev** [comment]
Finally got it, thank you! The example (if you decide to add it later on) should probably include the default `*` scope too.

```cson
"*":
  # all current config
".md.text":
  whitespace:
    removeTrailingWhitespace: false
```
My confusion was caused by the lack of context in the example. Might be worth adding it to save others from the same pitfall.

**Comment by burodepeper** [comment]
Thanks, I will, and it's silly that your own solution didn't work. Anyway, good luck, and I hope I've regained a user! ; )

**Comment by Morikko** [comment]
Hi, today I faced the same problem and hopefully I found your solution. Thanks a lot!

However, the solution is hidden in a closed issue.
Wouldn't it be good to add a note in the README ? Either to link to that post or to a clear message directly ?

**Comment by burodepeper** [comment]
@Morikko Very true, and I suppose I had planned to add it to the [FAQ](https://github.com/burodepeper/language-markdown/blob/master/FAQ.md). I'll re-open this and add it there, and possibly extend the README to include at least (some of) the topics covered in the FAQ.

**Comment by Morikko** [comment]
Ah Yes!  Into the FAQ, it would be great.

**Comment by burodepeper** [comment]
Update FAQ and README
