### ISSUE TITLE
Misinterpreted HTML target attribute values like _blank

### ISSUE THREAD

**Issue by revelt** [burodepeper/language-markdown#118]
Hi all,
Sometimes I write HTML in my .md and when it's link, I use `target="_blank"`.
This gets misinterpreted on the markdown parser as beginning of the underline.
Let's add exception for the following not to be parsed (including double quotes probably, to differentiate from real occurrences):

    "_blank"
    "_self"
    "_parent"
    "_top"

These are all possible values of HTML `target` attribute.

**Comment by burodepeper** [comment]
Thanks for reporting, I'll look into it.

**Comment by burodepeper** [comment]
@revelt I'm unable to replicate this issue; see the attached screenshot.

Could you verify that:
- You have the latest version of `language-markdown` and Atom installed;
- `language-gfm` is disabled, or enabled but that `language-markdown` is really selected;
- You have `language-html` enabled.

If that doesn't solve anything:
- What theme are you using? (shouldn't affect the parser though)
- Do you have any additional interfering or Markdown related packages installed?
- Could you post a screenshot that shows what's happening?

![schermafbeelding 2016-06-13 om 12 48 24](https://cloud.githubusercontent.com/assets/3703530/16005056/7f0037e8-3165-11e6-9e1a-c1a18cfce3f0.png)

**Comment by revelt** [comment]
Thank you, I'll check tonight and report back.

**Comment by revelt** [comment]
Hi @burodepeper thanks for the solution.

I actually didn't even have the `language-markdown` installed apparently! Once installed, all is well!

It's strange, why is `language-markdown` not the default markdown parser in Atom? Your parser is superior and should be bundled with Atom. Who is the best person(s) at Atom to approach regarding this?

**Comment by burodepeper** [comment]
Thanks!

No idea who to approach, but you could ask around on Slack. I don't mind it the way it is right now actually. Of course, it's nice to see more happy users, but that's not why I maintain this thing. I started this package because I wasn't too content with how `language-gfm` parses stuff, and PRs to that package didn't come through/took too long. There are some issues regarding syntax-theme support though (long, long story), and to be honest, I'd say that's a fair reason not to force a package switch on all users.

**Comment by revelt** [comment]
I see! So basically impossible... Anyway, thanks for your time, I really appreciate that.

I'll try to write a blog article and explain everybody they must install `language-markdown` on top of Atom and not rely on default parser.

**Comment by burodepeper** [comment]
Nah, not impossible, but to be honest, I like how it has been growing organically. I haven't promoted it, at least not much. I've only mentioned it in a handful places, but people seem to like it, and it is slowly spreading. A blog article would be nice. Send me a link when it's up, will you?
