### ISSUE TITLE
Extra spaces at the end of line are lost on save

### ISSUE THREAD

**Issue by Pablo-Leon** [burodepeper/language-markdown#122]
Those are needed, at least to the p[review pane, for multiline quuote text, Ex:

> line 1 (spaces here are significant)
> line 2
> line 3

regards
- Pablo

**Comment by burodepeper** [comment]
I think this is a duplicate of #115, and fortunately (for me) an issue with the `whitespace` package. See [this comment](https://github.com/burodepeper/language-markdown/issues/115#issuecomment-222129531) for instructions on how to fix it. You can close this issue if that solves your problem.
