### ISSUE TITLE
Syntax highlighting breaks

### ISSUE THREAD

**Issue by Stanzilla** [burodepeper/language-markdown#123]
after backticks are used, see 
http://i.imgur.com/JLdsTFY.png

**Comment by burodepeper** [comment]
Thanks for reporting. I expect this is related to #121. Could you verify this for me by changing `lua` on line 27 to `js`?

**Comment by Stanzilla** [comment]
That makes it only a little bit better: http://i.imgur.com/5JXOiyS.png

**Comment by burodepeper** [comment]
Hmm, that is not what I was hoping for. I'll have a better look at it. Will keep you updated.

**Comment by burodepeper** [comment]
Added support for `Lua` and a fallback for generic fenced-code-blocks. I'll publish an update in a few minutes. Let me know if this solves your issue.

![schermafbeelding 2016-07-09 om 13 13 17](https://cloud.githubusercontent.com/assets/3703530/16707668/fffc82a4-45d6-11e6-9e1c-35b59b5e64c3.png)

**Comment by Stanzilla** [comment]
That looks a bit better indeed http://i.imgur.com/zz0zAmY.png thank you!

**Comment by burodepeper** [comment]
Ah good, that looks how I would expect it from one of the default themes. Give `minimal-syntax-dark` a try if you want to see a wider range of supported elements. In the `README` are a few additional syntax-themes that provide pretty good support. The default themes work good with regular programming languages, but are rather limited when it comes to Markdown for instance.
