### ISSUE TITLE
Add new list item : Double list element after pressing ENTER

### ISSUE THREAD

**Issue by AntoineLT** [burodepeper/language-markdown#129]
I have an issue with the 'Add new list item' feature which I've never had before.
I don't know why but every time I press ENTER in a list with asterisks a second asterisk spawns (cf. picture below)

![markdown](https://cloud.githubusercontent.com/assets/14274310/17549127/276a16fe-5eef-11e6-8f88-df068f8bffbe.png)

**Comment by burodepeper** [comment]
Could you try reloading Atom? I've noticed this before, and it might be related to #72.

**Comment by AntoineLT** [comment]
After a full restart of Atom the feature  works well again ! 
I think you're right about the issue #72

**Comment by AntoineLT** [comment]
I updated, this morning, from the last update released (so I expect 0.16.1) to v0.16.2 because I was up to date in my Atom packages yesterday !

**Comment by burodepeper** [comment]
Okay, thank you!
