### ISSUE TITLE
Add new list-items ERROR when press ENTER

### ISSUE THREAD

**Issue by concefly** [burodepeper/language-markdown#130]
Hi.

I'm using version 0.16.2.

It seems that there are something wrong with the `Add new list-items` function.

![image](https://cloud.githubusercontent.com/assets/6647656/17836092/0b00f1e0-67b9-11e6-8d94-4ea13a674909.png)

When I type a list item and press ENTER, it will add four `-` automatically.

Nothing changes even if I reinstall it.

I have no idea about this now....

**Comment by burodepeper** [comment]
Have you tried restarting Atom?

**Comment by concefly** [comment]
It works.

Thx 👍
