### ISSUE TITLE
Table delimiters broken when not using :

### ISSUE THREAD

**Issue by tpoisot** [burodepeper/language-markdown#131]
In the alignment line, any `|` not directly followed / preceded by a `:` is not detected as alignment, but as storage.

**Comment by burodepeper** [comment]
Could you be more specific in what happens vs. what you expect?

**Comment by tpoisot** [comment]
![screenshot from 2016-08-28 15-12-21](https://cloud.githubusercontent.com/assets/579329/18036151/d908da9e-6d31-11e6-8c7c-cbf1b789a65e.png)

Both of the pipes that are blacker *should* have `punctuation.md`.

**Comment by burodepeper** [comment]
Okay, thanks for clarifying. I'll have a look at it.

**Comment by burodepeper** [comment]
Should be fixed in `v0.16.3`. Let me know if it works for you.

**Comment by tpoisot** [comment]
:+1:
