### ISSUE TITLE
Spell-check not available

### ISSUE THREAD

**Issue by orschiro** [burodepeper/language-markdown#134]
Dear @burodepeper,

I noticed that there is no spell-check when using `Markdown` as a language. 

Do you know why?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18622853/8c22718a-7e35-11e6-9317-c08f9d3f886a.png)

![image](https://cloud.githubusercontent.com/assets/170947/18622857/96bc65b0-7e35-11e6-8a81-9fa62375406b.png)

**Comment by burodepeper** [comment]
The default `spell-check` package doesn't scan documents in the `text.md` scope. You can add this yourself easily.

- Open the Atom settings, and find the Packages tab.
- Search for the `spell-check` package under the Core Packages.
- Open the Settings for `spell-check`
- Add `text.md` to the list of grammars
- Probably reload Atom to make sure the updated settings take effect

**Comment by orschiro** [comment]
Perfect solution.

Thank you very much, @burodepeper! :-)

-Robert
