### ISSUE TITLE
Please provide hint in README for how to enable spell-check

### ISSUE THREAD

**Issue by tluge** [burodepeper/language-markdown#135]
Spell-check is by default disabled for texts parsed by language-markdown. The reason is that the text is not considered part of the scope source.gfm any more, which is among the default scopes to which spell-check is applied. In its settings, spell-check can be applied to text parsed by language-markdown by manually adding the scope "text.md". While this can be found out with some digging, it would be great, if the README file provided a hint for this.

**Comment by burodepeper** [comment]
Good idea, I'll soon add this.

**Comment by burodepeper** [comment]
Done!
