### ISSUE TITLE
Incorrect highlighting when line begins with `~` (backtick, tilde, backtick)

### ISSUE THREAD

**Issue by aryzing** [burodepeper/language-markdown#136]
Beginning a line with the sequence `` `~` `` causes the entirety of the rest of the file to be highlighted as if it were inline code. Take a look (image is cropped at text wrap margin).

![screenshot from 2016-10-03 19-19-26](https://cloud.githubusercontent.com/assets/4924405/19046661/b5de6c08-899e-11e6-9a6b-b3c0a71d3a61.png)

**Comment by burodepeper** [comment]
Thanks for reporting, I'll have a look at it. I think I know what the problem is.

**Comment by burodepeper** [comment]
I can't replicate this issue, or well, I found another issue when trying to replicate it, but I can't replicate your issue. See this screenshot:

![schermafbeelding 2016-10-04 om 11 36 56](https://cloud.githubusercontent.com/assets/3703530/19069393/0d4d99fe-8a27-11e6-8fc9-66b17f320424.png)

Could you first try reloading Atom (packages sometimes behave unexpected, for unknown reasons), and if that doesn't help, could you paste the entire document in which you had the error in a Gist or a Pastebin? Maybe there's something else in there that's causing the issue.

And thirdly, could you try removing the `sh` on line 83, just to see if that makes a difference. There's a longstanding issue that some embedded grammars do not exit properly, and I just want to take that out of the equation by treating the code-block as generic source code.

**Comment by aryzing** [comment]
* Reloading packages did not work (ctrl+alt+r on linux).
* Gist [here](https://gist.github.com/aryzing/dc297d6373254ae0dd9b71ff9d3928b8).
* removal of `sh` did not work.

Let me know if you need anything else.

**Comment by burodepeper** [comment]
Thanks. Can you confirm that you are using the latest version of Atom (1.10.2) and of `language-markdown` (0.16.3), and that you are using this package and not accidentally `language-gfm` (it should say Markdown in the bottom right-hand corner of the window, not Github Markdown)?

I'm also not able to reproduce the issue with the data from your gist. Are there by any chance other Markdown-related packages you have installed that might interfere? And what syntax-theme are you using? (I don't think that is an issue, but it might help with replication)

**Comment by aryzing** [comment]
Aha! You are right! I was using `language-gfm` and not your `language-markdown`. Yours works as expected :)

**Comment by burodepeper** [comment]
Yay! I like me some problems that solve themselves! : )
