### ISSUE TITLE
Default Editor Soft Tabs Set to 4. Can't set tab length back to 2. 1 and 3 are working fine.

### ISSUE THREAD

**Issue by bradlis7** [burodepeper/language-markdown#140]
### Description

I'm just taking a guess, but it seems like when I try to use a default value, it wants to unset it, but it's inheriting 4 from my default editor configuration. I don't think this is an Atom issue, as language-python saved the value of 2.

The placeholder text says "Default: 2" in the language , but in reality, it is 4

### Steps to Reproduce

1. Set editor default soft tabs to 4
2. In a specific language, try to set soft tabs back to 2 (I was using language-markdown add-on).
3. It changes the text to 4.

### Versions

atom 1.11.1
language-markdown 0.16.3

**Comment by burodepeper** [comment]
I've had this problem before, though it's not specific to `language-markdown`. Those editor settings are automatically added to each language-package by Atom, but you can edit them manually. I've always considered them quite buggy, so I change things directly in `config.cson`. Open that via the main menu in Atom, and look for `.md.text` settings. It should be at the top level of the document, so abstracted, your config should look something like:

``` cson
"*":
  core:
    # ...
  editor:
    # this is where the default tab-length goes
    tabLength: 4
  "language-markdown":
    # this is where the private settings for language-markdown go
".md.text":
  # this is where the .md.text specific settings go
  # note that it's on the same level as "*"
  editor:
    tabLength: 2
```

I hope that helps.

**Comment by bradlis7** [comment]
That works! Should this be a bug for Atom? I do see the same thing in the php-twig package.

**Comment by burodepeper** [comment]
I think it should. If you can structurally reproduce it, and also show that the approach above fixed it, then you should submit it to as an issue. It looks like enough evidence for them to look for a solution. I can't imagine this is limited to `language-markdown`.
