### ISSUE TITLE
Support for JSON front matter?

### ISSUE THREAD

**Issue by gkjpettet** [burodepeper/language-markdown#141]
Would it be possible to add support for JSON front-matter? The static site generator Middleman supports this as a format as below:

```
;;;
    "title": "spf13-vim 3.0 release and new website",
    "description": "spf13-vim is a cross platform distribution of vim plugins and resources for Vim.",
    "tags": [ ".vimrc", "plugins", "spf13-vim", "vim" ],
    "date": "2012-04-06",
    "categories": [
        "Development",
        "VIM"
    ],
    "slug": "spf13-vim-3-0-release-and-new-website"
;;;

Markdown Content of the file goes **here**.
```

I have no idea how to make the changes myself but given there is comprehensive support for JSON syntax highlighting and your plugin already supports YAML and TOML front matter, I'm hoping it's not too hard to support.

**Comment by burodepeper** [comment]
Sure, shouldn't be an issue, I think. Can you look up the official documentation on this?

**Comment by gkjpettet** [comment]
Brilliant. Sure. Essentially, the fencing for the JSON front matter is ;;; (rather than +++ for TOML and --- for YAML).

Not sure what documentation you require but here is some below if it helps:

[Middleman documentation](https://middlemanapp.com/basics/frontmatter/)
[Official JSON docs](http://json.org)
[language-json for Atom](https://atom.io/packages/language-json)

**Comment by burodepeper** [comment]
Thanks. That's all I need. Unless I run into any issues you can expect this to be part of the next release.

**Comment by gkjpettet** [comment]
Great - thank you so much. Absolutely no pressure but what kind of time frame are you looking at?

**Comment by burodepeper** [comment]
Probably today

**Comment by burodepeper** [comment]
![schermafbeelding 2016-10-18 om 12 34 24](https://cloud.githubusercontent.com/assets/3703530/19474485/17d37506-9530-11e6-992b-fabfbdc5c955.png)

**Comment by burodepeper** [comment]
Done. `v0.17.0` is live.

**Comment by gkjpettet** [comment]
Wow. Thanks a lot!
