### ISSUE TITLE
Bold code affects highlighting inside math-mode blocks

### ISSUE THREAD

**Issue by codebje** [burodepeper/language-markdown#145]
With a math-mode expression such as `$f \in \{0,1\}^*\to\{0,1\}^*$`, the asterisks inside are treated as enabling emphasis.  Updating the grammar to recognise that `$…$` is an inline-math and `$$…$$` is a block math section would be useful for those of us using a flavour of markdown which accepts math.

**Comment by burodepeper** [comment]
Agreed, and I've been planning to look into this for a while now. Could you point me to documentation regarding maths in Markdown?

**Comment by burodepeper** [comment]
- http://math.stackexchange.com/editing-help#latex
- https://github.com/cben/mathdown/wiki/math-in-markdown
- http://csrgxtu.github.io/2015/03/20/Writing-Mathematic-Fomulars-in-Markdown/

I haven't researched it properly, but as far as I can tell mathematics are generally written as LaTeX and embedded inline with single dollar signs, and as embedded blocks with a double dollar sign.

It wouldn't be to difficult to have `language-latex` parse the contents of these blocks, if installed. Any additions?

**Comment by codebje** [comment]
I mostly use [Pandoc's Markdown](http://pandoc.org/MANUAL.html#pandocs-markdown) where the math extension is described [here](http://pandoc.org/MANUAL.html#math).  The markdown-preview-plus plugin recognises the Pandoc style, and renders with MathJax.

**Comment by burodepeper** [comment]
From the Pandoc spec:

> Anything between two $ characters will be treated as TeX math. The opening $ must have a non-space character immediately to its right, while the closing $ must have a non-space character immediately to its left, and must not be followed immediately by a digit.

Your example `$f \in \{0,1\}^*\to\{0,1\}^*$` does not follow this rule. Do you know what the consensus about this is? I need to know how to distinguish the math markup from sentences that contain dollar signs where they're used to identify variables for instance.

**Comment by codebje** [comment]
The example inline in other Markdown looks like:

```
Given some function $f \in \{0,1\}^*\to\{0,1\}^*$, there must exist ...
```

This satisfies the rule that the opening $ has a non-space character to its right ("f" in this case), the closing $ has a non-space character to its left ("*"), and is not followed by a digit.  The rule means that expressions such as `$f \equiv $` fail to render, as there's white-space immediately before the closing $.

**Comment by burodepeper** [comment]
Oh wow, my bad, I completely misread it, haha, _getting caffeine now_...

Anyway, this shouldn't be a big issue to add to the package, but I don't want to push updates too often. Should be in the next update though. Hope you can live with the inconvenience a little longer!

**Comment by codebje** [comment]
Yes, most of the time I don't really even notice, but I hit a case where I had unbalanced asterisks inside an expression and had the emphasis style leak out all over subsequent text :-)

Thanks for taking the bug into account!

**Comment by burodepeper** [comment]
Needs some testing, but initial detection works pretty okay. Syntax highlighting of inline math is done via `language-latex`.

![schermafbeelding 2016-10-19 om 14 39 34](https://cloud.githubusercontent.com/assets/3703530/19518928/e289ebca-9609-11e6-8410-9778d1207316.png)

**Comment by burodepeper** [comment]
Changes added to `dev` branch, and will be part of next release.

**Comment by burodepeper** [comment]
Update is published!

**Comment by laughingrice** [comment]
I opened a different ticket, but it probably belongs as a comment here.

The new update breaks syntax highlighting pretty badly.

The minor part is that if there is more than one equation on the same line, the whole section between the first and the last $ signs is marked as math. Something like this is a good example

    the reference image $I_r$ and the template image $I_t$.

The much bigger issue is with display math. If there is anything after the closing $$, including a white space, the rest of the file is marked as math mode. This completely breaks pandoc-crossref which uses {#eq:label} after the closing $$ to reference the equation like this

    $$
    d_y(x) = D \del{f_r(x), f_t(y)}
    $$ {#eq:dist}

In this case I have 2/3 of the file highlighted as an equation
