### ISSUE TITLE
Imports snippets from language-gfm (and possibly extend them)

### ISSUE THREAD

**Issue by brandoncurtis** [burodepeper/language-markdown#147]
By default, this package automatically indents lists when you press tab or shift-tab.  This prevents snippet usage in Markdown lists.  It's not currently possible to indent only on shift-tab.  If tab and shift-tab could be independently enabled and disabled, the user could indent with shift-tab and activate snippets with tab.

**Comment by burodepeper** [comment]
Not a snippet user myself; my apologies for overlooking this. Could you give me an example of one or more snippets used in combination with Markdown where this could be a common issue in lists?

> If tab and shift-tab could be independently enabled and disabled, the user could indent with shift-tab and activate snippets with tab.

I think a better solution would be to "allow" snippets to be executed before a line-indent/outdent is executed. <kbd>tab</kbd> and <kbd>shift-tab</kbd> are the default for in- and outdenting in code-editors. I'd like to avoid creating a new paradigm for such common behavior.

**Comment by brandoncurtis** [comment]
\*headdesk\* of course shift-tab outdents, my bad.

A common Markdown-specific snippet inserts a link: `[$1]($2) $3`

Markdown list users greatly outnumber snippet users (and snippet users can always map different keys to expand a snippet or indent a list), so the current behaviour is probably fine.

**Comment by burodepeper** [comment]
Nah, I'm keeping this open for a little investigation of myself. If I can give snippets preferred execution, then that would be a solid solution. If that turns out to be a big deal, I can at least at something to the README about changing the keymapping. Thanks for reporting!

**Comment by brandoncurtis** [comment]
If you find out more about the feasibility of preferred execution, I'd love to hear about it!  Many packages could benefit from this if it's relatively straightforward to implement.

**Comment by burodepeper** [comment]
I'm thinking of adding some of these: https://github.com/atom/language-gfm/blob/master/snippets/gfm.cson

**Comment by brandoncurtis** [comment]
Yes!  Those are the snippets I use, plus a few custom ones.

**Comment by burodepeper** [comment]
To be precise: have you added those snippets manually to your custom snippets?

**Comment by burodepeper** [comment]
I've added the following to my custom snippets, and they are executed before the indent-list-item action. Could you paste the contents of your custom snippets here? Perhaps it's nothing more than a typo.

```cson
'.text.md':
  'image':
    prefix: 'img'
    body: '![$1]($2)$0'
  'link':
    prefix: 'link'
    body: '[$1]($2)$0'
```

**Comment by brandoncurtis** [comment]
This had definitely never worked for me, so yesterday I had temporarily unchecked 'indent list-items' in the language-markdown settings.  Upon re-checking that same box (and making no change to my snippets), snippets now work perfectly in Markdown lists.  ooof.

**Comment by burodepeper** [comment]
Let's blame buggy Atom, agreed? ;)

Next time something doesn't work as expected (pretty much in any package, even in the core packages), try reloading Atom (<kbd>Cmd+Alt+Ctrl+L</kbd> on Mac). In other cases, you know where to find me.

I'm keeping this open until I've added the snippets from `language-gfm`. If you have any interesting additions, let me know.
