### ISSUE TITLE
Support for highlighting language-mathematica in the markdown file

### ISSUE THREAD

**Issue by Edenharder** [burodepeper/language-markdown#148]
[language-mathematica](https://github.com/Fitzse/language-mathematica) 

Thanks for your work!

**Comment by burodepeper** [comment]
Done. I plan to publish an update this weekend.

![schermafbeelding 2016-10-27 om 12 52 24](https://cloud.githubusercontent.com/assets/3703530/19764671/81f75842-9c44-11e6-8698-0cac582e2cf3.png)

Would you mind looking up a good example of some Mathematica code for me? I'd like to add support for it to my syntax-themes.

**Comment by Edenharder** [comment]
I'd like to, but what do you mean by "a good example of some Mathematica code"? Could you explain it?

**Comment by burodepeper** [comment]
A sample that shows the diversity of what one might encounter in real life. That way I get an idea of what type of elements are part of the syntax (I've looked at the docs, but without examples it's not an easy read for this purpose) and how best to style them.

**Comment by Edenharder** [comment]
Generally, the own editor of Mathematica does not provide too much highlighting (right one in the figure), while the package of atom [language-mathematica](https://github.com/Fitzse/language-mathematica) provides more (left one).
![image](https://cloud.githubusercontent.com/assets/6672134/19771486/5e1446dc-9c63-11e6-8095-f7e6c02b97bb.png)
Maybe you can just use the syntax highlight of language-mathematica. If you want to do it from beginning, the following two links maybe also help:

1. [Wolfram Language Syntax](https://reference.wolfram.com/language/guide/Syntax.html)
2. [Overview Of Mathematica Syntax](http://www.math.umn.edu/~rogness/lg3d/mma_syntax.html)

**Comment by burodepeper** [comment]
Thanks, I believe that's enough.

And yep, I'm simply including `language-mathematica` when it's requested. Seems a bit overkill to write another grammar parser myself ; )

**Comment by burodepeper** [comment]
Update is published!
