### ISSUE TITLE
Issue with not recogonized fenced code block

### ISSUE THREAD

**Issue by 4Oranges** [burodepeper/language-markdown#149]
If there is an fenced code block with not recognized language, for example
<pre><code>
\`\`\`lang1                                    (1)
...
\`\`\`                                         (2)

# Heading 1                                    (3)

\`\`\`lang2                                    (4)
\`\`\`                                         (5)
# Heading 2                                    (6)
</code></pre>

The highlighting parser not recognizes the `lang1` in line `(1)`, so it skip this line and do nothing, just treat it as normal text, since it's a valid fenced code block starting.
Then, the parser recognized the line `(2)` as a starting of a fenced code block since it should be recognized as the ending of the fenced code block starting at line `(1)`.
As a result, the line `(3)`, `(4)` which are not in any fence code block are now in a fenced code block, therefore, the headign in line `(3)` and code block starting in line `(4)` are not recognized correctly, until the parser  finds the ending marker at line `(5)` of the code block starting with `(2)`
This should be considered as a bug.

**Comment by burodepeper** [comment]
I believe I had fixed this problem earlier, see #123. Can you verify that you are using the vanilla version of the package, and not your own current dev version? I can't replicate the issue following your example. See the screenshot below:

![schermafbeelding 2016-10-29 om 08 35 49](https://cloud.githubusercontent.com/assets/3703530/19827691/ea112ccc-9db2-11e6-91ef-1bd1b366376a.png)

**Comment by 4Oranges** [comment]
It seems my working branch is out of date, sorry for the mistake, I'm
closing this issue.

**Comment by burodepeper** [comment]
Don't worry about it. It's good that you're keeping an eye out for stuff like this!
