### ISSUE TITLE
Closing of math sections is wrongly detected for both inline and displayed math

### ISSUE THREAD

**Issue by laughingrice** [burodepeper/language-markdown#153]
For inline math, if there are two math sections they are detected as one, so for the following example the whole section between the first and last $ signs is marked as math instead of two separate sections

    the reference image $I_r$ and the template image $I_t$.

For displayed math, if there is any character (including a space) after the closing $$ sign, the rest of the file is marked as a math section which does not work with pandoc-crossref syntax as an example. So after this equation, the rest of the file is highlighted as math mode

    $$
    d_y(x) = D \del{f_r(x), f_t(y)}
    $$ {#eq:dist}

As well as for this simpler case

    $$
    d_y(x) = D \del{f_r(x), f_t(y)}
    $$ |

(note that there is a trailing space after the closing $$ sign)

**Comment by burodepeper** [comment]
Thanks for reporting. Having a look at it now. Shouldn't be a difficult fix.

**Comment by burodepeper** [comment]
Path `v0.18.1` released! Let me know if you run into any other issues.

**Comment by laughingrice** [comment]
Thank you. Perfect now
