### ISSUE TITLE
It seems impossible to enter either the @ or ! symbol in a document

### ISSUE THREAD

**Issue by laughingrice** [burodepeper/language-markdown#154]
Pressing @ and ! call the markdown:link and markdown:image keybindings, which on the one hand seem to do nothing (nothing happens to the marked text), but on the other, make it impossible to actually enter these characters in the document.

Interestingly I just tested _,* and ~ and they seem to both modify the text while at the same time entering the character, so while it allows to enter those characters, we also get a spurious character.
So highlighting bold and pressing * gives **bold***. A solution would probably be to enter one less character at the end of the word, although that doesn't work with removing the effect.

**Comment by burodepeper** [comment]
Try reloading Atom

**Comment by laughingrice** [comment]
Thanks, my bad, I should have caught this one.

**Comment by burodepeper** [comment]
No problem. It seems to be an issue with Atom itself when adding certain
new stuff to a package in an update. Have reported the issue to them a
while back, but to no avail yet.
