### ISSUE TITLE
Checking language of code fence

### ISSUE THREAD

**Issue by jfiksel** [burodepeper/language-markdown#166]
Hey there--I'm writing a package that correctly indents R code, and I was wondering if there is a way to pull out whether or not you're in a fence code. For example, if I'm working in a .Rmd file and I have
```
```{r}
code
"```"
```

(ignore the quotation marks), would there be a way to pull out the fact that I'm now in an R code fence?

**Comment by burodepeper** [comment]
Hey there you too. There's nothing pre-made for that purpose. What might interest you (in the sense that you could borrow some code from it) is another package I've been working on, see: https://github.com/burodepeper/mark-code-blocks

The idea behind that package is that it detects certain code blocks by scope name, and adds custom classes to both the lines and line numbers. The "detects certain code blocks by scope name" is what you're looking for. Embedded R has the scopeName `embedded.source.r`.

I hope that helps.
