### ISSUE TITLE
Not seeing language-markdown grammar classes in DOM

### ISSUE THREAD

**Issue by rkpatel33** [burodepeper/language-markdown#167]
I started playing around with custom styling for markdown based on the `language-markdown` grammar but when I looked at the inspector I noticed I am not seeing the classes defined in the package (`heading-1.md`). Instead, I am seeing classes that follow the pattern `syntax--heading-1`:

![image](https://cloud.githubusercontent.com/assets/3799489/23097949/b87642fa-f5f6-11e6-97ea-e5eb618bd530.png)

I have syntax `Markdown` selected for the file. I also have the One Dark UI theme and Cobalt 2 syntax theme activated. Is the Cobalt theme somehow interfering with it?

**Comment by burodepeper** [comment]
See [this blog](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html) for details, and [the markdown styles](https://github.com/burodepeper/minimal-syntax/blob/master/styles/markup-and-down.less) from one of my themes for an example.

In essence, Atom prefixes all scopes added by grammars with `syntax--` to avoid conflicts with global scopes of the same name. Just add the prefix to _each_ className in your theme, and you should be fine. If you forget one, the deprecation cop in Atom will show a warning.

**Comment by rkpatel33** [comment]
Got it, thanks!
