### ISSUE TITLE
italics and bold in same line fails

### ISSUE THREAD

**Issue by tpoisot** [burodepeper/language-markdown#17]
This is *not* the expected behavior:

![capture d ecran de 2015-10-01 11-32-48](https://cloud.githubusercontent.com/assets/579329/10225336/6f105308-6830-11e5-9fa9-4c9f75788047.png)

**Comment by burodepeper** [comment]
I know.

**Comment by tpoisot** [comment]
Some additional info:

![capture d ecran de 2015-10-01 11-34-24](https://cloud.githubusercontent.com/assets/579329/10225388/a10a3216-6830-11e5-95cf-2a778caa9496.png)

**Comment by tpoisot** [comment]
@burodepeper :+1: on the quick response

**Comment by burodepeper** [comment]
I know that aswell! : )
I've accidently pushed a version with a regexp that's a bit too eager, because I wanted to get something out (with better scopes, so that people can actually use it), but then I gave up after a long day. Will look at it over the weekend. Need to rewrite the specs for emphasis as well to the new format, because that makes testing things way faster.

**Comment by burodepeper** [comment]
Oh, a little side note.
Please try not to call them italics and bold; they are _emphasis_ and **strong emphasis**. I've also written some background reasoning in the README, and it might be a good idea to give some tips on _how to use_, can't find the right words at the moment.

**Comment by tpoisot** [comment]
Right, so let's call them *foo* and **bar**, but the point is: it doesn't work. I think going full pedantic on users is not a good move, since most people will be looking for how to achieve a given effect (namely, italics and bolds) as opposed to the underlying semantics.

**Comment by burodepeper** [comment]
![schermafbeelding 2015-10-02 om 10 50 57](https://cloud.githubusercontent.com/assets/3703530/10242766/84af0d80-68f3-11e5-81cf-8fe7fa4985f6.png)

Work in progress, and I'd prefer your input to be a little more constructive than a (bluntly perceived) _it doesn't work_. I hope you are aware that my efforts in rewriting the entire markdown package are voluntary, and that you are free to use or develop a different tool than mine if you don't agree with certain decisions.

That said, give it a little patience. It is not even at `0.1.0` yet...

**Comment by tpoisot** [comment]
Raising the issue and indicating additional circumstances when the issue happened. The point of issues is when things don't work.

I know that open source is voluntary, but I also know that being offended when people point out bug is not beneficial.
