### ISSUE TITLE
Atom 1.15: Highlighting stops after a certain line length

### ISSUE THREAD

**Issue by sbaack** [burodepeper/language-markdown#170]
I installed Atom 1.15 yesterday and some of the changes seem to conflict with language-markdown. In longer paragraphs, the syntax highlighting just stops after a certain (fixed?) line length. To illustrate the issue:

![screen shot 2017-03-10 at 6 35 04 pm](https://cloud.githubusercontent.com/assets/8274140/23806186/fe683be0-05c0-11e7-8cac-18054f1ff085.png)

language-gfm does not have this issue:

![screen shot 2017-03-10 at 6 34 35 pm](https://cloud.githubusercontent.com/assets/8274140/23806225/1defaa3e-05c1-11e7-8934-7f7a66f2488f.png)

**Comment by burodepeper** [comment]
Very probably related to this: https://github.com/atom/language-gfm/pull/187

Will verify and publish update hopefully tomorrow.

**Comment by burodepeper** [comment]
Oh wow, I did not know commits could auto-close issues.

**Comment by sbaack** [comment]
Thank you for fixing this so quickly!

**Comment by burodepeper** [comment]
I published v0.20.0 with this fix.
