### ISSUE TITLE
embed language-make can't work for fenced code block

### ISSUE THREAD

**Issue by barrygu** [burodepeper/language-markdown#180]
@burodepeper 

Using language-markdown:
![image](https://cloud.githubusercontent.com/assets/7963691/26622832/43b8aa16-461e-11e7-9f7d-ba62dc65dffd.png)

Using language-gfm-enhanced:
![image](https://cloud.githubusercontent.com/assets/7963691/26622847/5867d4dc-461e-11e7-9e94-247b81a01db2.png)

Could you enable it?
Thanks a lot.

**Comment by burodepeper** [comment]
Sure, shouldn't be a big issue. You can expect it in the next update.

Note for self: https://github.com/shd101wyy/language-gfm-enhanced/blob/master/grammars/gfm.cson#L764-L780

**Comment by burodepeper** [comment]
I've published v0.23 and language-make should now be supported. Let me know if you run into any issues with this.
