### ISSUE TITLE
Create symbol for headers

### ISSUE THREAD

**Issue by leesei** [burodepeper/language-markdown#181]
Is it possible to create symbol for headers so that I can use <kbd>Ctrl</kbd>+<kbd>R</kbd> (with [goto](https://atom.io/packages/goto)) to jump to headers?

**Comment by burodepeper** [comment]
That would be something for the goto package to implement. It maintains an [internal list of selectors](https://github.com/v3ss0n/goto/blob/master/lib/symbol-generator.coffee#L7-L11) to detect and index symbols. There is an [old issue](https://github.com/v3ss0n/goto/issues/52) over there that discusses this, but it appears to have become stale. I would suggest that you submit a [new issue](https://github.com/v3ss0n/goto/issues/new) on the goto repository to get the ball rolling again.

**Comment by leesei** [comment]
Thanks for the pointer.
