### ISSUE TITLE
The C++ code is not distinguished properly in code block

### ISSUE THREAD

**Issue by HidekiHokuto** [burodepeper/language-markdown#182]

**Comment by burodepeper** [comment]
Can you give an exact (code) example of what happens, and what you had expected it to do?

**Comment by EroMonsterSanji** [comment]
I found not only the “*”, but the c++ code cannot be highlighted properly.




I think the "*pre = NULL” here was detected as italic...

**Comment by burodepeper** [comment]
Can you paste the C++ code so I can try the code myself?

**Comment by EroMonsterSanji** [comment]
The return, int are not highlighted for this

```cpp
class Solution {
public:
    /**
     * @param triangle: a list of lists of integers.
     * @return: An integer, minimum path sum.
     */
    int minimumTotal(vector<vector<int> > &triangle) {
        if (triangle.empty()) {
            return -1;
        }

        int result = dfs(0, 0, triangle);

        return result;
    }

private:
    int dfs(int x, int y, vector<vector<int> > &triangle) {
        const int n = triangle.size();
        if (x == n) {
            return 0;
        }

        return min(dfs(x + 1, y, triangle), dfs(x + 1, y + 1, triangle))  + triangle[x][y];
    }
};
```
The `*pre = NULL` is highlighted as italic
```cpp
ListNode *ReverseList(ListNode *head) {
    ListNode *pre = NULL, *tmp;
    while(head) {
        tmp=head -> next;
        head -> next = pre;
        pre = head;
        head = tmp;
    }
    return pre;
}
```

The return, int are not highlighted

**Comment by burodepeper** [comment]
I've seen that happen before, and I believe it is related to these language-gfm issues: https://github.com/atom/language-gfm/issues/45 and https://github.com/atom/language-gfm/issues/40

I'm afraid there's not much I can do about it, since it isn't directly related to this package. You can try escalating the linked issues since they've become rather stale.
