### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by AutuanLiu** [burodepeper/language-markdown#184]
why not support [KaTeX](https://khan.github.io/KaTeX/) in the future version? And please take this suggestion if it is appropriate.

Thank you!

**Comment by burodepeper** [comment]
Could you be more specific?

KaTeX appears to be a visualizer for LaTeX, so I'm not sure how you see it fit in with a grammar package. Maybe you'd want it to be part of the preview? In that case, try submitting the idea to the [markdown-preview](https://github.com/atom/markdown-preview) package.

**Comment by AutuanLiu** [comment]
According to your reply, I have seen the [relevant issue][1] in [markdown-preview][2], and thank you for your patience. :laughing: 

[1]:https://github.com/atom/markdown-preview/issues/116
[2]:https://github.com/atom/markdown-preview
