### ISSUE TITLE
Highlight "setext-style" headers (-- and ==)

### ISSUE THREAD

**Issue by vjpr** [burodepeper/language-markdown#185]
My headers using atx-style appear blue.

But when using settext-style (https://daringfireball.net/projects/markdown/syntax#header) they are not.

**Comment by burodepeper** [comment]
I'm aware of this issue. The simple answer: the way Atom allows to parse content doesn't allow the detection of new lines in a pattern, which is needed to detect setext-style headers. See the [FAQ](https://github.com/burodepeper/language-markdown/blob/master/FAQ.md#which-elements-of-markdown-are-supported) on this. Unless the way grammars work are fundamentally changed, setext headers simply can't be implemented.

**Comment by 73** [comment]
The [language-gfm Issue](https://github.com/atom/language-gfm/issues/211) is still open as well...
