### ISSUE TITLE
Cannot type ! and @ if link shortcuts are disabled

### ISSUE THREAD

**Issue by mp4096** [burodepeper/language-markdown#188]
Hi and thanks for the package!

### Setup

Ubuntu 16.04, Atom 1.18.0 and `language-markdown` 0.25.0 __with 'Link shortcuts' disabled__

### Expected behaviour

`Shift + 1` should result in `!`, `Shift + 2` should result in `@`.

### Observed behaviour

Nothing happens, the keystrokes are silently consumed by `markdown:image` or `markdown:link`

### First occurrence

I could trace this behaviour to cb14cc73ad9f1e86f549f9716006884ea5c71a83

**Comment by burodepeper** [comment]
Ah, thanks, good catch. Will get a patch out as soon as possible.

**Comment by burodepeper** [comment]
I published v0.25.1 which should fix this. Could you verify it for me?

**Comment by mp4096** [comment]
Yep, now it works like a charm, thanks!
