### ISSUE TITLE
Section titles are not hi-lighted

### ISSUE THREAD

**Issue by kmace** [burodepeper/language-markdown#195]
When using language-gfm, titles such as:
`## Title` get syntax hi-lighting whereas with this package does not.

**Comment by burodepeper** [comment]
Can you post a screenshot showing the difference? And can you tell me what syntax-theme you are using?

**Comment by kmace** [comment]
My apologies. I did not read that only certain syntax-themes worked. 

I was using Nebula, but It works with a supported syntax theme such as Pubster

**Comment by burodepeper** [comment]
No problem. If you point the author of a syntax-theme to this repo, it should be trivial for them to add support for this package.

**Comment by kmace** [comment]
I'll do that.
