### ISSUE TITLE
Match language by full name for code blocks

### ISSUE THREAD

**Issue by Siguza** [burodepeper/language-markdown#196]
This leads to correct highlighting:

    ```js
    window.alert('derp');
    ```

While this does not:

    ```JavaScript
    window.alert('derp');
    ```
For reference, here on GitHub both work the same:

```js
window.alert('derp');
```

```JavaScript
window.alert('derp');
```

**Comment by burodepeper** [comment]
I'll have a look soon, shouldn't be a problem.

**Comment by burodepeper** [comment]
It seems that the convention for code blocks is to write the language names (as they are supported by the grammar) in all lowercase letters. I'd prefer not to make an exception just for this, so I'm closing the issue. If you feel obliged, feel free to rewrite the pattern matching to be case-insensitive, and submit a PR for it.
