### ISSUE TITLE
Following Failed to load the language-markdown package #176

### ISSUE THREAD

**Issue by EdiMund** [burodepeper/language-markdown#198]
Hi team,

I installed the package via the Atom interface. I followed the instructions (disabled language-gfm), closed Atom and reopened. Reboot my PC and still I am experiencing the same issue described above (Failed to load the language-markdown package At Cannot find module 'season').

What would you recommend me to do?

Disabling all language packages also does not work.

Thanks
:-)

**Comment by burodepeper** [comment]
Sorry that it has been so long. I'm sure you've given up on this by now. If not, before I have a look at it, has it since resolved itself due to perhaps an Atom update?

**Comment by Nydia07** [comment]
You should look at your environment variable,the 'Path' of user variable should set where your atom installed,and find the directory of 'npm',such as 'C:\Users\NY\AppData\Local\atom\app-1.28.2\resources\app\apm\node_modules\npm'.

I changed Path before,and now I change it back,then it work out.Hope my answer can hlep you!
In a word,if you install atom and nodejs in default installation path,you will reduce a lot of troubles.
