### ISSUE TITLE
Breaks Cobalt2 themes markdown highlighting when uninstalled

### ISSUE THREAD

**Issue by twhite96** [burodepeper/language-markdown#199]
I installed this package and noticed my pretty cool syntax highlighting with Wes Bos's Cobalt 2 theme was completely broken so I uninstalled your package. Now, none of the markdown highlighting works in Atom. Not sure if it is on your end or Wes's but I'm kinda bummed.

**Comment by burodepeper** [comment]
Re-enabling the original built-in `language-gfm` package should do the trick.

**Comment by burodepeper** [comment]
Additionally, you can also ask the cobalt2 theme author to add some styling for this package. It's not that much work, but your markdown experience will improve a lot.

**Comment by twhite96** [comment]
Thanks. I will close this out now and ask Wes for a little help in the markdown syntax department. 😃

**Comment by burodepeper** [comment]
Cool. Let me know when he has adapted his theme. Might be interesting for other users as well!
