### ISSUE TITLE
@user versus @citationkey

### ISSUE THREAD

**Issue by tpoisot** [burodepeper/language-markdown#2]
Here is a suggestion. In gfm, `@user` mentions a user. In pfm, `@citationkey` cites an item in the bibliography.

Ideally, the package would be able to separate the two, as a function of the markdown flavor being used.

**Comment by burodepeper** [comment]
Noted. But aren't they both a subclass of a sort of `reference`?

**Comment by tpoisot** [comment]
So `punctuation.reference` for `@`, then `user.reference` and `bibkey.reference` depending on the syntax? I could really live with this (since as I mention in #5, critic markup also has support to reference users).

**Comment by burodepeper** [comment]
Yeah, something along those lines.

**Comment by tpoisot** [comment]
By the way, references in pandoc *can* include `_`:

> Each citation must have a key, composed of ’@’ + the citation identifier from the database, and may optionally have a prefix, a locator, and a suffix. The citation key must begin with a letter, digit, or _, and may contain alphanumerics, _, and internal punctuation characters (:.#$%&-+?<>~/).

**Comment by burodepeper** [comment]
I haven't had time to look at the promised/intended Pandoc side of the project. I was hoping that @leipert would largely do this, but he's really busy at the moment. On a suggestion by @simurai, I'm currently thinking about different ways in which the base package could be extended. Our original intention to implement a form of dynamic grammar proves to be rather resource intensive. I like the way the base linter and its extension work.

**Comment by burodepeper** [comment]
@tpoisot I am cleaning up old issues, and I'm wondering if your views on this topic have changed. I've put `pandoc` in general on a bit of a hold, because I'm rather unfamiliar with it. I'm still interested in extending this package though.

From a syntax-highlighting point-of-view, I wonder if it that is important to (visually) distinguish between different types of references. I've implemented several types of references within the gfm-realm, and while working on my theme, I keep coloring them the same since there is (in my tests at least) little confusion within context. Knowing that something is a valid reference seems to be enough. If you have a different opinion (preferable with a use-case), I'm open to suggestions.

Programmatically, I think it could be an interesting feature to distinguish between types of references (as there is between distinguishing types of lists, etc.), but the primary use-case I keep thinking of is in the linting realm, and therefore outside of the scope of this package. Again, your thoughts are welcome.

**Comment by tpoisot** [comment]
Sorry for the epic necrobump, but what about `_` in citations? Should I go ahead and submit a PR?

**Comment by burodepeper** [comment]
I'm afraid this kind of slipped my mind. I'll have a look at it soon,
especially the _.

**Comment by burodepeper** [comment]
@tpoisot 

> You can also write an in-text citation, as follows:
```
@smith04 says blah.
@smith04 [p. 33] says blah.
```

How common is this usage/pattern for citations? It's easy to distinguish citations when they are found within square brackets, but these inline citations are pretty much the same thing as github usernames for instance.

**Comment by burodepeper** [comment]
I've implemented the citation references that occur in brackets according to the Pandoc specs. See #106 for details.

> In the en-US locale, locator terms can be written in either singular or plural forms, as book, bk./bks.; chapter, chap./chaps.; column, col./cols.; figure, fig./figs.; folio, fol./fols.; number, no./nos.; line, l./ll.; note, n./nn.; opus, op./opp.; page, p./pp.; paragraph, para./paras.; part, pt./pts.; section, sec./secs.; sub verbo, s.v./s.vv.; verse, v./vv.; volume, vol./vols.; ¶/¶¶; §/§§.

I'm considering including the above as well. It might be overkill, but the abstracted pattern `[label][space][number, or range]` is specific enough not to cause too many false positives. @tpoisot, what do you think?

**Comment by tpoisot** [comment]
The in-text pattern is fairly common. Pandoc defines a citation as `@` followed by a unique id (which is the same way github defines mentions). The brackets around are just to indicate that the citation should be encloses in parentheses:

`@doe2004` = `Doe et al. (2004)` or `Ref. 1`
`­[@doe2004]` = `(Doe et al., 2004)` or `[1]`

**Comment by burodepeper** [comment]
Okay, thanks, makes sense. I'm currently using [https://github.com/burodepeper/language-markdown/blob/pandoc-citations/spec/fixtures/flavors/pandoc.ass](these) as tests. Can you think of any additional test-cases that could cause problems?

I'm going to combine the current `gfm` mentions and `pandoc citations` into generic references. There's no way to distinguish between them anyway, and I don't think there's any significant pros into separating them (visually). A reference is a reference. I hope to publish an update sometime later this week.

**Comment by tpoisot** [comment]
Quite sure these are the only use cases. I agree that both are generic references, too.

**Comment by burodepeper** [comment]
I've just published a new release that adds these generic references. I'm closing this issue. Let me know if you run into any further issues.
