### ISSUE TITLE
Trailing whitespaces trimmed with `Keep Markdown Line Break Whitespace` option

### ISSUE THREAD

**Issue by claudiofantacci** [burodepeper/language-markdown#200]
Hi everyone,
I know this has been a topic of discussion some months ago (see #115 and the [FAQ](https://github.com/burodepeper/language-markdown/blob/master/FAQ.md#trailing-whitespace-is-automatically-removed-but-i-dont-want-that)), however it is not clear to me whether the package is in sync with the `whitespace` package option `Keep Markdown Line Break Whitespace`.

I have been discussing this with the `whitespace` maintainers [here](https://github.com/atom/whitespace/issues/166#issuecomment-338898694) and from our test it seems that the problem is related with this package which does not "parse" the `Keep Markdown Line Break Whitespace` option.
This new option should avoid users to add
```cson
'*':
  # all current config
'.md.text':
  whitespace:
    removeTrailingWhitespace: false
```
in the `config.cson`. Am I right?

**Comment by burodepeper** [comment]
It is related to [this issue](https://github.com/atom/whitespace/issues/137) on the whitespace package. It checks whether the document scope matches that set by Atom's default language-gfm package, and not for the default scope from language-markdown.

I can make/submit the PR that's suggested in that thread, but it will have to wait until I'm less busy with my normal work. If that PR is accepted, it should indeed remove the need for the setting you quoted.

**Comment by ehaynes99** [comment]
Why was this closed? It's still a problem...

**Comment by burodepeper** [comment]
@ehaynes99 This issue isn't closed; some issues on a different repo that referenced this issue were.

**Comment by ehaynes99** [comment]
Oops, geez, don't I feel foolish. My mistake.

**Comment by burodepeper** [comment]
I've submitted a PR that should fix this issue: https://github.com/atom/whitespace/pull/177

**Comment by burodepeper** [comment]
PR has been merged. I expect it to be part of the next update of Atom
