### ISSUE TITLE
ampersand among markdown text is changing color of all following text

### ISSUE THREAD

**Issue by Dowwie** [burodepeper/language-markdown#201]
When I include an ampersand followed by an alphabetical character in markdown text, all of the paragraphs of text that follows the ampersand changes color.  If the ampersand is proceeded by a symbol, such as a period or underscore, the text color does not change.

**Comment by burodepeper** [comment]
This appears to be an issue with the language-html package (which is included in language-markdown to supply support for html) in [this pattern](https://github.com/atom/language-html/blob/master/grammars/html.cson#L394-L409).

Could you paste the text in which you legitimately ran into this issue? That would make it easier to submit an issue or PR that's going to be approved.

**Comment by Dowwie** [comment]
The following two paragraphs differ by the user of a proceeding symbol after the ampersand.  The first paragraph _does not_ lead to an unwanted color change of the rest of the paragraph.  The second paragraph _does_ lead to an unwanted color change.

&.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.


&Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Comment by burodepeper** [comment]
: ) I had already replicated the issue. What I meant was, could you paste an actual example of one of your texts in which you ran into this issue?

**Comment by Dowwie** [comment]
@burodepeper wheel spinning.
