### ISSUE TITLE
Atom crashes when editing markdown table

### ISSUE THREAD

**Issue by kylebarron** [burodepeper/language-markdown#205]
Atom crashes while editing a markdown table with this package activated. If I type
```
| Filename | Description of Report |
|-|-||
     ^
```
where my cursor is the `|` character directly above the `^`; then if I hit `tab`, Atom will crash every time. In my terminal, after Atom crashes, I see 
```
/usr/bin/atom: line 129: 11384 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
```
If I disable `language-markdown`, then restart Atom, Atom does not crash in this situation. When I enable the package again, and restart Atom, Atom again crashes.

My Atom version is:
```
> atom --version
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
This also crashes on Atom 1.22.1 and Atom 1.24.0-beta1. I'm using Ubuntu 16.04.

**Comment by burodepeper** [comment]
Hmm, if I follow your exact steps, I can't replicate the issue.

Could you include a list of all other packages you have installed?

**Comment by kylebarron** [comment]
Sorry to hear that.
```
> apm list --installed --bare
language-markdown@0.25.1

Hydrogen@2.1.1
Zen@0.18.0
aligner@1.2.4
aligner-javascript@1.3.0
aligner-python@1.1.0
atom-alignment@0.13.0
atom-beautify@0.30.9
atom-clock@0.1.15
atom-ide-ui@0.7.0
atom-material-syntax@1.0.7
atom-material-ui@2.0.6
atom-terminal@0.8.0
auto-detect-indentation@1.3.0
autoclose-html@0.23.0
autocomplete-R@0.6.0
autocomplete-bibtex@1.1.0
autocomplete-paths@2.12.1
autocomplete-python@1.10.5
busy-signal@1.4.3
change-case@0.6.5
color-picker@2.2.5
cson@2.0.1
css-snippets@1.1.0
docblockr@0.13.4
editor-stats@0.17.0
file-icons@2.1.15
fonts@3.0.3
git-control@0.9.0
git-plus@7.10.0
git-time-machine@1.5.9
grammar-token-limit@0.1.1
highlight-line@0.12.0
highlight-selected@0.13.1
hydrogen-launcher@1.2.1
indent-guide-improved@1.4.13
ink@0.7.11
insert-timestamp@0.2.4
intentions@1.1.5
julia-client@0.6.6
language-julia@0.14.0
language-latex@1.1.1
language-liquid@0.6.0
language-markdown@0.25.1
language-matlab@0.2.1
language-pfm@0.82.0
language-r@0.4.2
language-restructuredtext@1.1.0
language-sas@0.2.4
language-stata@1.3.0
latex@0.49.0
latex-completions@0.3.3
latexer@0.3.0
linter@2.2.0
linter-flake8@2.3.0
linter-shellcheck@1.4.6
linter-ui-default@1.6.10
linter-write-good@0.9.0
markdown-preview-plus@2.4.16
markdown-writer@2.7.3
minimap@4.29.7
minimap-bookmarks@0.4.2
minimap-cursorline@0.2.0
minimap-find-and-replace@4.5.2
minimap-git-diff@4.3.1
minimap-highlight-selected@4.6.1
minimap-pigments@0.2.2
minimap-selection@4.5.0
minimap-split-diff@0.3.7
pdf-view@0.61.0
pigments@0.40.2
platformio-ide-terminal@2.7.0
project-manager@3.3.5
python-indent@1.1.4
python-tools@0.6.9
qolor@0.4.2
regex-railroad-diagram@0.19.4
remote-edit@1.9.0
script@3.18.0
sort-lines@0.18.0
split-diff@1.5.1
stata-exec@1.2.1
table-editor@0.2.2
teletype@0.4.0
toggle-quotes@1.1.0
tree-view-git-status@1.4.0
wakatime@7.0.4
wordcount@2.10.4
```

**Comment by burodepeper** [comment]
Okay, I do not immediately see any obvious culprits.

The only <kbd>TAB</kbd> related thing that language-markdown is indentation of list-items. You can disable that via the package settings (disable "Indent list-items", and then restart Atom, just to be sure).

If that doesn't solve the issue, I suggest crossposting this as an Atom issue. You can /cc me there so I can add my two cents.

Additional thought, do you have a platform other than Ubuntu to test this on?

**Comment by kylebarron** [comment]
I just tested this on macOS Atom version 1.23.1 and it doesn't crash, so it might just be Ubuntu. When I open Atom in Safe mode on Ubuntu, however, it doesn't crash. I'll do more debugging tomorrow. 

Thanks for your quick responses!

**Comment by kylebarron** [comment]
I'm pretty sure it was the [table-editor](https://github.com/klorenz/atom-table-editor) package. I disabled that and it works fine now.
