### ISSUE TITLE
snippets for .md and .rmd bug

### ISSUE THREAD

**Issue by HenrikEckermann** [burodepeper/language-markdown#207]
When I install language-markdown, my snippets stop working. I looked into the settings of language-markdown and tried to adapt my snippets but it does not work.

Here my snippets that work if language-markdown is not installed and language-gfm is enabled. The snippets do not work with language-gfm disabled OR with language-markdown installed (even if language-gfm is also enabled and disabling in the settings of language-markdown is disbaled.

Here is my snippet code:

```
'.source.pweave.md, .source.gfm, text.md':
  'python_chunk':
    'prefix': 'pp'
    'body': """
    ```{python$2}
    $1
    ```
    """

  'r_chunk':
    'prefix': 'rr'
    'body': """
    ```{r$2}
    $1
    ```
    """
```

**Comment by burodepeper** [comment]
The first line in your snippet code misses a period before `text.md` ; )

**Comment by HenrikEckermann** [comment]
Damn... I swear, it did not miss not all the time when I was experimenting what could be the cause. But yes...It works now. Sorry man...:)

**Comment by burodepeper** [comment]
Haha, no problem.
