### ISSUE TITLE
Cannot open markdown link, Plugin conflictss

### ISSUE THREAD

**Issue by dineshbhosale** [burodepeper/language-markdown#208]
### Description

Cannot open markdown link. The real cause of the problem is a conflict between `burodepeper/language-markdown` and `atom/link`

### Steps to Reproduce

1. Install this plugin -> https://github.com/burodepeper/language-markdown
2. Install this plugin -> https://github.com/atom/link/
3. Make sure both plugins are enabled at the same time
4. Create and open a new markdown file
5. Add link , for example 
```md
source : <https://github.com/GitbookIO>

[GitBook on GitHub](https://github.com/GitbookIO)

<https://github.com/GitbookIO>

[testLink1](https://github.com/GitbookIO)
```
6. Save file
6. Use command pallet to run `link: open`

**Expected behavior:**
Link opened in default browser chromium.

**Actual behavior:** 
Nothing happens, no error, nothing.

**Reproduces how often:**
Always when both plugins are enabled at the same time.

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

(node:24571) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
apm  1.18.11
npm  5.6.0
node 9.3.0 x64
atom 1.22.1
python 2.7.14
git 2.15.1

OS Manjaro Linux , everything is latest and up to date

### Additional Information

https://github.com/atom/link/issues/31#issuecomment-353679362
This issue was closed becaus eauthor said it's a problem with `burodepeper/language-markdown` and not with `atom/link`

https://github.com/atom/link/issues/24
This issue was opened by me, it was closed because it did not provide enough information. I did not provide information because I thought markdown links are not supported by `atom/link` plugin and developer will understand. The real cause of the problem is a conflict between `burodepeper/language-markdown` and `atom/link`

https://github.com/atom/link/issues/23
This issue was opened by another github user , it was closed because user was not able to provide enough information about the cause of this problem.

**Comment by burodepeper** [comment]
I'll have a look at it. Need to make sure that changing the link's scopes doesn't cause other issues. Should be an easy fix otherwise.

**Comment by dineshbhosale** [comment]
Thanks.

**Comment by burodepeper** [comment]
The conflict is resolved. Will be patched in the upcoming release.
