### ISSUE TITLE
Add .pmd and .jmd to filetypes

### ISSUE THREAD

**Issue by mpastell** [burodepeper/language-markdown#209]
Could you add (or accept a pull request) `.jmd` and `.pmd` to supported filetypes? This would enable previewing documents edited with https://atom.io/packages/language-weave.

**Comment by kylebarron** [comment]
This package isn't a markdown viewer. You have to look at [markdown-preview](https://atom.io/packages/markdown-preview) or [markdown-preview-plus](https://atom.io/packages/markdown-preview-plus) for that. This package does syntax highlighting for Markdown, so it would actually conflict with language-weave.

**Comment by burodepeper** [comment]
@mpastell Considering Kyle's remark, I'm not entirely sure what you're requesting. Could you make the PR yourself? That should clarify things.

**Comment by burodepeper** [comment]
I've had some time to look into this. Adding the filetypes would indeed only cause conflicts. Adding the to the fenced-code-blocks doesn't make sense to me. I'm closing this, but if you're still interested in adding this, submit a PR with a short explanation of what you intend to accomplish with it.
