### ISSUE TITLE
Parser screws up for empty code blocks

### ISSUE THREAD

**Issue by mcandre** [burodepeper/language-markdown#216]
The GitHub flavored markdown parser messes up when it encounters two consecutive backticks, representing an empty code snippet.

**Comment by burodepeper** [comment]
You've posted this in the wrong repo. I've verified that this is indeed an issue with the default language-gfm, but not with this package language-markdown. I suggest you either crosspost this to https://github.com/atom/language-gfm or switch to using this package.
