### ISSUE TITLE
Info: East End syntax supports language-markdown

### ISSUE THREAD

**Issue by MarcusE1W** [burodepeper/language-markdown#218]
Hi @burodepeper 

I have used your template to add support for language-markdown in these two syntax themes:
- [East End](https://atom.io/themes/east-end-syntax)
- [East End Notebook](https://github.com/MarcusE1W/eastend-notebook-syntax)

Any pointer as to what still can be improved are welcome.

If you are fine with the support I would appreciate if you could add the syntax themes to your README.

**Comment by burodepeper** [comment]
Cool, I'll have a look!

**Comment by burodepeper** [comment]
I've added your themes to the README. Should pop up with the next release, or commit, or something like that.
