### ISSUE TITLE
Support Kotlin highlighting

### ISSUE THREAD

**Issue by shd101wyy** [burodepeper/language-markdown#220]
Hi there,

First of all, thank you very much for creating this awesome package.
Could you please add support for Kotlin highlighting when you have chance?

Thank you very much.

**Comment by joeaniu** [comment]
+1

**Comment by burodepeper** [comment]
Sure, will do. I have a terrible backlog at the moment, but I have some free time coming up, and will start adding new things then.

**Comment by joeaniu** [comment]
Thank you!

**Comment by burodepeper** [comment]
Implemented. Will be part of next release.

![schermafbeelding 2018-06-15 om 17 46 02](https://user-images.githubusercontent.com/3703530/41477255-004e4520-70c4-11e8-8fb5-1bf8c6cde71a.png)
