### ISSUE TITLE
No highlighting for bold/italic

### ISSUE THREAD

**Issue by jon-wong-sutd** [burodepeper/language-markdown#223]
Is this the package that does highlighting for Markdown syntax?

I see `TODO` being made italic (and cyan), which would definitely confuse me trying to look for italicized text in my Markdown.

**Comment by hannwong** [comment]
Oops. Sorry. So syntax-themes are the ones doing the syntax highlighting. Pls close this issue! Thanks!

**Comment by burodepeper** [comment]
No problem, just wanted to reply to you.

**Comment by qwiglydee** [comment]
Why it works with language-gfm without any additional efforts but not with this package?

**Comment by burodepeper** [comment]
> Why it works with language-gfm without any additional efforts but not with this package?

Because they are different packages... and as suggested earlier, it's up to the syntax-theme to make these decisions. Language-markdown does not give explicit instructions on how something is supposed to be rendered, neither does language-gfm.

**Comment by qwiglydee** [comment]
It's absolutely unclear how to make the theme work with the package, while the same theme works with gfm out-of-the box.

**Comment by burodepeper** [comment]
@qwiglydee Is it your own theme? Have you read the documentation for Atom on how to make a theme? Have you looked at [this bit of the docs of this package](https://github.com/burodepeper/language-markdown/blob/master/CONTRIBUTING.md#syntax-theme-support)?

**Comment by qwiglydee** [comment]
Does that mean that I need to create my own theme to work with markdown?
Why can't I use built-in or usual "monokai"? I prefer to have colors consistent across all languages I use.

**Comment by burodepeper** [comment]
@qwiglydee You can extend themes (read the docs), you can re-use colors from that theme. Or you can ask the authors of those themes to better support this package. Not much that I can do for you there. If that's an issue for you, it's probably easier for you to switch back to language-gfm.
