### ISSUE TITLE
Missing tried-and-tested syntax-theme?

### ISSUE THREAD

**Issue by hannwong** [burodepeper/language-markdown#224]
According to the [FAQ](https://github.com/burodepeper/language-markdown/blob/master/FAQ.md#some-of-my-markdown-elements-arent-highlighted), there should be some tried-and-test syntax-themes "*featured above*" (that FAQ entry).

Where is it?

**Comment by burodepeper** [comment]
In the README, [here](https://github.com/burodepeper/language-markdown#syntax-theme-support).
