### ISSUE TITLE
missing line numbers

### ISSUE THREAD

**Issue by juancarloscastillo** [burodepeper/language-markdown#229]
Hi, just a small question of an inexperienced user: I noticed that when using this package the line numbers in the editor disappear ... is there a way to show them ? Thanks, and btw great package!

**Comment by burodepeper** [comment]
Hi @juancarloscastillo, your issue is most likely caused by another package. Can you post a list of the packages you have installed? From memory, if you have the `typewriter` package installed, that one is most likely the culprit.

**Comment by juancarloscastillo** [comment]
Thanks for the quick response @burodepeper ; You were right, I checked and finally discovered it: it was the "zen mode" of markdown-preview-enhanced (@shd101wyy)  which was activated in my editor. Best!

**Comment by kylebarron** [comment]
This can probably be closed.
