### ISSUE TITLE
Yaml syntax highlighting

### ISSUE THREAD

**Issue by baurigae** [burodepeper/language-markdown#23]
First of all I commend you for taking the time to write and maintain this package & am very grateful for the effort.

Now, the issue: before updating to v. 0.0.12, I had no YAML syntax highlighting whatsoever. After the update, I have this: 

![md](https://cloud.githubusercontent.com/assets/5447269/10530916/211f8024-73ac-11e5-9f99-8d6142448dca.png)

For comparison, under GMF, I have this:

![gmf](https://cloud.githubusercontent.com/assets/5447269/10530940/4d09067e-73ac-11e5-84a5-17c5c34011c2.png)

I'm running Atom 1.0.19 on Ubuntu 15.04

**Comment by burodepeper** [comment]
Hi @baurigae, thank you, and you're welcome.

About your issue, this explains one of the peculiarities I found in `language-gfm`. It allowed `---` as a delimiter for something, if I remember correctly. Do you per change know where this markup comes from? Where I can find some documentation on it?

For now, I would suggest you use `fenced code blocks`. Github has some trouble displaying Markdown in Markdown, so I'll try describe it. Fenced code blocks use three backticks (again, can't use markdown to write markdown) or `~~~` as delimiters (before and after) and you specify a language by adding it to the first: for example `~~~markdown`

The example below shows the markdown for your yaml, but ignore the backslashes. I had to put them in to display the backticks.

~~~markdown
/```yaml
layout: post
title: Title
tags: [one,two,testing]
image:
  credit:
  etc: "..."
/```
~~~

Let me know if this works out for you.

**Comment by burodepeper** [comment]
And thanks for being the first _unofficial_ user! : )

**Comment by tpoisot** [comment]
I was thinking about the same issue -- jekyll, and pandoc, use yaml to encode some metadata. Maybe the syntax for fenced code blocks can be adapted to include the `language.yaml` grammar?

**Comment by burodepeper** [comment]
The issue is that `---` is considered a `horizontal-rule` and (in the same sense as with setext headers) I'm unable to detect what comes after. So any implementation will be a bit sketchy.

There is something in `language-gfm` that intends to support this, but I'd need some examples to test that it doesn't interfere with anything else. If you can provide those, I'll take a jab at it.

```cson
  {
    'begin': '\\A---$'
    'end': '^(---|\\.\\.\\.)$'
    'captures':
      '0':
        'name': 'comment.hr.gfm'
    'name': 'front-matter.yaml.gfm'
    'patterns': [
      {
        'include': 'source.yaml'
      }
    ]
  }
```

Also, it mentions front-matter, any idea what that refers to?

**Comment by tpoisot** [comment]
Yes, the front-matter is the bit of YAML at the top of the document. Actually, maybe that can help: the front-matter is supposed to start on the very first line. 

Here are to examples:

~~~ md
---
front: matter
...

This is a paragraph

---

then another one
~~~

and

~~~ md
---
front: matter
---

This is a paragraph

---

then another one

---

and a third
~~~

**Comment by burodepeper** [comment]
Ok thanks. I'm really unfamiliar with YAML. Could you Google me some official documentation/specs on this? True, I'm a little lazy, but you probably better know what I need, than I do.

**Comment by tpoisot** [comment]
Here's jekyll -- http://jekyllrb.com/docs/frontmatter/

and pandoc -- http://pandoc.org/README.html#epub-metadata

**Comment by burodepeper** [comment]
Thanks, I'll look into it.

**Comment by burodepeper** [comment]
Support for `yaml-front-matter` added to master-branch. I'll release an update later this weekend.

**Comment by baurigae** [comment]
Sorry for the very late reply - well all I have to say at this point is thanks very much for fixing this!

**Comment by burodepeper** [comment]
@baurigae Not a problem. Good to know that your problem is solved.
@tpoisot Can you confirm this for your documents too?

**Comment by tpoisot** [comment]
Yes, working great. :+1:
