### ISSUE TITLE
Support Typescript highlighting

### ISSUE THREAD

**Issue by joeaniu** [burodepeper/language-markdown#230]
Hi burodepeper,  I can't live without your awesome package!   

Could you please add support for typescript highlighting when you have time ?

Thank you!

![image](https://user-images.githubusercontent.com/2009190/42406478-0f9fa258-81db-11e8-86f1-4b288aad0de7.png)

**Comment by burodepeper** [comment]
Hey @joeaniu, thanks for the compliment! What package do you use for Typescript highlighting? Shouldn't be an issue adding that to the next release.

**Comment by joeaniu** [comment]
![image](https://user-images.githubusercontent.com/2009190/42944263-c2c39dec-8b97-11e8-82ef-39056ef74e79.png)
I am using markdown-preview-enhanced 0.15.6 and language-markdown 0.26.0 as attached image show.

**Comment by kylebarron** [comment]
@joeaniu He means the package for TypeScript highlighting. Are you using the base [language-typescript](https://github.com/atom/language-typescript) package?

**Comment by joeaniu** [comment]
@kylebarron yes, I am using language-typescript 0.3.3
![image](https://user-images.githubusercontent.com/2009190/43750715-3caa4258-9a2c-11e8-9a0e-e1806b9b0fc6.png)
