### ISSUE TITLE
Support numbered lists

### ISSUE THREAD

**Issue by kylebarron** [burodepeper/language-markdown#231]
It looks like https://github.com/burodepeper/language-markdown/pull/94 was meant to fix this, but it doesn't work for me in the latest version. I could be interested in sending a PR for this.

![peek 2018-08-03 11-39](https://user-images.githubusercontent.com/15164633/43652094-35e4efb2-9712-11e8-9f4f-04fdba015a19.gif)

**Comment by burodepeper** [comment]
Blank list items get removed, check: https://github.com/burodepeper/language-markdown/blob/master/lib/main.js#L55-L60

It's meant for when you're at the end of a list, then it'll remove the last, empty list item, so you can just press enter twice. I believe most word processors implement something similar.

**Comment by kylebarron** [comment]
Sorry! I should have known that behavior from the lists.

**Comment by burodepeper** [comment]
No problem, and you _shouldn't_ anything. Thanks for all your help by the way! Appreciate it a lot
