### ISSUE TITLE
Is it possible to define custom spacing between list markers and list content

### ISSUE THREAD

**Issue by kallsey** [burodepeper/language-markdown#238]
It would be useful to be able to specify the spacing between list markers and list content for auto-indenting. 

Example: The default is one space. I'd like to use three spaces for unordered lists and two for ordered lists.

**Comment by burodepeper** [comment]
That would indeed be an interesting, although rather niche feature. I've been considering similar things (such as setting the correct numbers in ordered lists when saving a document, etc.) but I think they are outside of the intended scope of this package. I'm open to accepting PRs that implement these kinds of behavior as opt-in features.

**Comment by kallsey** [comment]
thanks!

**Comment by burodepeper** [comment]
Hey @kallsey,
#240 has introduced a new feature which keeps the amount of whitespace equal to your last list-item. This is no 100% fix for your request, but it would help you a bit.
