### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Arcanemagus** [burodepeper/language-markdown#24]
This package is failing to install for me on:
Atom 1.0.19
Windows 8.1 x64

```
Installing “language-markdown@0.1.0” failed.

> runas@2.0.0 install C:\Users\Landon\AppData\Local\Temp\apm-install-dir-115921-231128-1opv8ga\node_modules\language-markdown\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild


C:\Users\Landon\AppData\Local\Temp\apm-install-dir-115921-231128-1opv8ga\node_modules\language-markdown\node_modules\pathwatcher\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\Landon\AppData\Local\atom\app-1.0.19\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Landon\\AppData\\Local\\atom\\app-1.0.19\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Landon\\AppData\\Local\\atom\\app-1.0.19\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Landon\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Landon\\.atom\\.apmrc" "install" "C:\\Users\\Landon\\AppData\\Local\\Temp\\d-115921-231128-m1k57s\\package.tgz" "--target=0.30.7" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.
```

From a bit of searching it almost looks like I would need to install VS2013 (or higher)? https://github.com/chjj/pty.js/issues/60

As this hasn't been required for any other Atom package that seems a bit odd...
If you need any more information please let me know.

**Comment by burodepeper** [comment]
That is weird. I will look into this tomorrow.

**Comment by burodepeper** [comment]
@Arcanemagus I've checked and updated the dependencies (I saw we used an older version of pathwatcher) so perhaps this might do the trick. Could you un- and re-install the package to see if this solves this?

**Comment by burodepeper** [comment]
@Arcanemagus Another user on Windows had the same issue, and it appeared to be because of a wrong version of Python. I have no idea where that comes into play. Anyway, try running `npm install runas` from the `language-markdown` directory, or perhaps install it globally. If things go according to plan, it will fail building `runas` and show some more specific output. After that I'm afraid I can't help you any further than by directing you to their repository. Let me know how things play out.

**Comment by Arcanemagus** [comment]
Yep, definitely looks like an issue with the `runas` repository. Although I'm not seeing the python issue (I have 2.7.10 installed).

I've filed https://github.com/atom/node-runas/issues/19 over there. Marking this as closed since it's not an issue with this package :wink:.

**Comment by burodepeper** [comment]
Thanks for reporting the issue anyway!

**Comment by Arcanemagus** [comment]
So it might be quite simple to work around this in this package. You are requiring `node-pathwatcher`, which is what is requiring `node-runas`, which is what is causing all these issues.

From what I could see looking over the code, the only place you are utilizing this is [here](https://github.com/burodepeper/language-markdown/blob/adc2be218d6268e452337bf26febbc75c68ef933/lib/main.coffee#L44) to synchronously get a listing of files. Is there a reason you are using this package instead of a simpler method?

**Comment by burodepeper** [comment]
I found the `Directory` class as part of the Atom API so I thought it would be safe to use. Apparently not, or I'm requiring the 'wrong' pathwatcher. But as you suggest, there might be a simpler way of getting the list of files, probably via `fs`. I'll have a look at that. Thanks for your help!

**Comment by burodepeper** [comment]
Hey @Arcanemagus, I've just published a `v0.1.2` version that doesn't depend on `pathwatcher` directly, but requires Directory as provided by Atom. I assume this should work better. Would you mind giving the update a try?

**Comment by Arcanemagus** [comment]
Sure, I'll try it when I get into work tomorrow, thanks!

**Comment by Arcanemagus** [comment]
Sorry it took so long to get back to you, `v0.1.2` installed with no issues.

**Comment by burodepeper** [comment]
Not a problem, and thanks for checking!
