### ISSUE TITLE
Syntax errors in code blocks break subsequent markdown highlighting

### ISSUE THREAD

**Issue by rdominy** [burodepeper/language-markdown#241]
If you have a code block that has a syntax error (e.g., json with no close brace), all markdown highlighting after the code block is broken.

Expected behavior:  The code block end should take priority and end that section allowing normal markdown parsing to resume.

Example:

```javascript
{
	
```

This is **not** highlighted correctly

**Comment by burodepeper** [comment]
Thanks for reporting. This is a known issue in the first-mate core package of Atom. See https://github.com/atom/first-mate/pull/90 for a related PR and reasoning for why it's not being actively pursued. Closing this because it's an issue with first-mate.
