### ISSUE TITLE
Strings with curly braces in R markdown breaks highlighting

### ISSUE THREAD

**Issue by stefanocoretta** [burodepeper/language-markdown#247]
In a .Rmd document, if a chunk option has a string containing curly braces, highlighting breaks if the Markdown grammar is selected. (Latest Atom version and language-markdown version).

In the following example, the chunk option `fig.cap` is a string with a LaTeX command using curly braces (`\\Cref{s:pilot}`).

<img width="795" alt="Screenshot 2019-05-13 at 13 01 19" src="https://user-images.githubusercontent.com/6429302/57616764-47f44d00-757f-11e9-9b84-fb5f825111ed.png">

If the closing brace is removed, highlighting is restored.

<img width="751" alt="Screenshot 2019-05-13 at 12 54 28" src="https://user-images.githubusercontent.com/6429302/57616441-5c841580-757e-11e9-9891-6700c68012c5.png">

**Comment by burodepeper** [comment]
![Schermafbeelding 2019-05-22 om 14 36 24](https://user-images.githubusercontent.com/3703530/58174833-1118e800-7c9f-11e9-80be-7d212ae4c86c.png)

Issue is solved in upcoming version
