### ISSUE TITLE
Unable to use autocomplete for unusual words using square brackets "[]" in scientific paper

### ISSUE THREAD

**Issue by mjsielerjr** [burodepeper/language-markdown#257]
Hi there,

I'm writing a scientific paper that's about some chemicals that use "[]" in their names. For example, "benzo[a]pyrene" or "B[a]P".  I'd like to be able to not have to continually type this word over and over but the brackets in the word seem to be preventing autocompletion to work. When I go to type benzo[a]pyrene it will only autocomplete to benzo, then I have to type "[a]" myself, and then when I start typing pyrene it will autofill that (see images below). 

![image](https://user-images.githubusercontent.com/6273555/79906911-9041ff00-83cd-11ea-94bf-2900b494f022.png)
![image](https://user-images.githubusercontent.com/6273555/79906937-9c2dc100-83cd-11ea-9e24-1f8a8a0f695c.png)

Otherwise autocompletion works fine with other common and uncommon words I'm using.

**Comment by burodepeper** [comment]
That is an interesting issue.

I don't think this is a language-markdown issue, but I might be able to help you. In Settings > Editor is an option called Non Word Characters. These characters define word boundaries and [ and ] are among them. These are probably also used when indexing words for autocompletion. Try removing [ and ] from this list, then restart Atom, and see if it helps.

Word of warning: this will have an impact on programming languages if you also use Atom for programming. It probably won't break anything, but it will likely be (mildly) inconvenient.

**Comment by mjsielerjr** [comment]
Hi @burodepeper,

Thanks for the quick reply. Instead of going to general settings > editor, I went into the language-markdown settings and deleted the "[]" from the Non Word Characters like you suggested and it worked (see pic below)! I tried replicating this inside a python file and it didn't work, so that appears to be the best solution for getting around the Non Word Character issue in markdown files and not have it affect other file formats! 

This will save me so much time! Is there anyway I can make a little donation to you for your help/work on this awesome package?

<img width="352" alt="image" src="https://user-images.githubusercontent.com/6273555/80006285-8675d580-8479-11ea-8c47-ca98a9e0b2c1.png">

<img width="352" alt="image" src="https://user-images.githubusercontent.com/6273555/80006316-91c90100-8479-11ea-89b5-3f813f10f1a2.png">

**Comment by burodepeper** [comment]
You're welcome! I didn't think of changing it only for language-markdown; an even better solution! What is your paper about, if I may ask?

If you'd like, you can send a donation to my PayPal (see my profile for my email), but you'd make me equally happy by donating to something environmental. I haven't set up anything specific for it, because you would be my first donateur! :)

**Comment by mjsielerjr** [comment]
> You're welcome! I didn't think of changing it only for language-markdown; an even better solution! What is your paper about, if I may ask?

Sure! Thanks for asking :) I'm studying the gut microbiome (microbes that live in our intestines) to see if it digests pollutants (e.g. benzo[a]pyrene, found in smoke or burnt food) and in turn how those digested pollutants might influence how our brain grows in early life. It appears that the microbiome does have an influence on neurological development of young zebrafish, but we need to do more studies to understand exactly why. 

> If you'd like, you can send a donation to my PayPal (see my profile for my email), but you'd make me equally happy by donating to something environmental. I haven't set up anything specific for it, because you would be my first donateur! :)

Great idea, I'll do both ;)
