### ISSUE TITLE
Add Markdown Extra flavor

### ISSUE THREAD

**Issue by burodepeper** [burodepeper/language-markdown#37]
See: https://michelf.ca/projects/php-markdown/extra/ and https://github.com/atom/language-gfm/issues/56

- [x] Add special attributes (`{#id .class key=value}`) to:
  - [x] Headings
  - [x] Fenced code blocks
  - [x] Links
  - [x] Images
- [x] Definition lists
- [x] Footnotes
- [x] Abbreviations

**Comment by bobrocke** [comment]
+1

**Comment by burodepeper** [comment]
Quick update on Markdown Extra implementation. I need to refactor some bits to add special-attributes to the fenced-code-blocks to avoid duplicate code. But the rest is coming along nicely:

![schermafbeelding 2015-11-13 om 09 25 57](https://cloud.githubusercontent.com/assets/3703530/11141775/bf7ac0d8-89e8-11e5-9b39-39591b1628f3.png)

**Comment by burodepeper** [comment]
I've just published a new version of the package, support for Markdown Extra included. Let me know if you run into any issues.

**Comment by IzzySoft** [comment]
> Let me know if you run into any issues.

Just did, @burodepeper : As soon as I enable it, no more preview (Ctrl-Shift-M or menu, doesn't matter) possible. Disable language-markdown, and preview works again (for already open documents, this even requires a restart of atom).

In case it matters: Ubuntu 12.04 here, atom installed via `.deb`, language-markdown via package GUI.

**Comment by burodepeper** [comment]
Hi @IzzySoft,
Thanks for reporting. See issue #51 for an interim fix. A PR has been submitted to the `markdown-preview` package, but until then, you'll have to do with the fix mentioned in #51.

**Comment by IzzySoft** [comment]
Thanks a lot, that did it!

Now I'm just missing the id/class stuff from *Markdown Extra* (e.g. `## Foobar { #foobar .foo }` to be converted to `<h2 id='foobar' class='foo'>Foobar</h2>`). Using that a lot for internal references etc.

**Comment by burodepeper** [comment]
You're welcome.

The Markdown Extra bits in combination with `markdown-preview` fall out of the scope of this package though. As far as I know, `markdown-preview` only supports _regular_ (or perhaps GIthub Flavored) Markdown. You could take a look at `markdown-preview-plus`, though I am not familiar with all the options that package supports: https://atom.io/packages/markdown-preview-plus

If `markdown-preview-plus` doesn't support the Markdown Extra bits, I suggest opening an issue over at their repository and ask for them to support the special-attributes.

**Comment by IzzySoft** [comment]
OK, thanks (btw: `markdown-preview` must at least support either M-Extra or Github-flavoured, as otherwise it wouldn't render tables correctly ;) MPP doesn't state supporting M-Extra (just takling about "pandoc support"), but I can give it a try of course.

Thanks again for your fast responses!

**Comment by burodepeper** [comment]
You're welcome.

And considering support by those packages, I suppose it is a bit of a gray area whether they are interested in it or not. The idea behind a preview package of course is that it gives you a preview of your content, or from a different perspective, whether your markdown renders as intended. The inclusion of the Markdown Extra special attributes would be something you'd want to be included when exporting (not previewing) or converting from Markdown to probably html in your case.

Anyhow, I hope they are able to help you further, and otherwise, consider creating the desired functionality yourself and PR it to `markdown-preview-plus`. The regular `markdown-preview` is a core package so I reckon they intend to support anything outside of Github Flavored Markdown.

**Comment by IzzySoft** [comment]
Thanks again, @burodepeper – but unfortunately I lack time and experience to jump in with a PR here (already too many other projects I'm involved with).

Export is a valid issue indeed – though I'm mainly concerned with a convenient WYSIWYG editor to prepare texts for my web sites, where they're then rendered via MichaelF's Markdown-Extra implementation. So I was investigating options. Being quite happy with ReText – but currently stuck with Ubuntu 12.04 and thus not able to install the latest version (the one running here has some issues with HTML comments).

I'll keep an eye on Atom (as I do with Haroopad and Remarkable). So far I didn't find an Atom plugin offering sufficient Markdown-Extra support (for those attributes), but apart from that it does fine :)
