### ISSUE TITLE
Add support for ERB to fenced-code-blocks

### ISSUE THREAD

**Issue by tarky** [burodepeper/language-markdown#43]
![2015-11-17 18 49 59](https://cloud.githubusercontent.com/assets/3303297/11208060/3fd5f48e-8d5c-11e5-9751-31e3ce38c699.png)

As you see above,  highlightings are broken, under the erb code block.
It seems some types of language don't work, though only ruby works. 

Does this project plan to support other language types?

**Comment by burodepeper** [comment]
Hi @tarky, thanks for reporting this issue.
I plan to support as many other language types as possible. See https://github.com/burodepeper/language-markdown/blob/master/grammars/fixtures/fenced-code.cson for the current list of supported languages. I expect to add `erb` in the next release.

**Comment by burodepeper** [comment]
On a side note, for now, I've chosen to expect fenced-code-blocks to have the same number of characters as its open and closing delimiters. I see in your example that you open with `~~~` (3) and close with `~~~~` (4). That's why they document isn't highlighted further down. If you run into any other issues, please do let me know.

**Comment by burodepeper** [comment]
I thought it would be simpler to add this, but I ran into a little problem, that seems related to https://github.com/atom/language-gfm/issues/40

Although (as shown below) the parsing is incorrect (that's a different issue, similar to #22), something in ruby is preventing the fenced-code-block from being closed. I will have to delve into this a little deeper.

![schermafbeelding 2015-11-17 om 12 34 34](https://cloud.githubusercontent.com/assets/3703530/11210348/e7ff3330-8d27-11e5-9221-2c29bf657817.png)

**Comment by tarky** [comment]
@burodepeper Thank you for detail explanation!
If you zoom up the image above, you can see closing delimiter is 3. The last one is  a line break symbol.
But I understand the situation. Anyway this project is great.

**Comment by burodepeper** [comment]
Ah, you are right about the closing parameter! My bad! : )
I will look into this later again. I'm bothered by the same thing happening with PHP code, which is also technically embedded inside HTML. I'll update this issue when I find out something new.

**Comment by burodepeper** [comment]
Closed in favor of keeping the issue centralized to #77.
