### ISSUE TITLE
Add support of mermaid diagrams like https://cloose.github.io/CuteMarkEd/ has

### ISSUE THREAD

**Issue by stasberkov** [burodepeper/language-markdown#44]
Add support of mermaid (https://knsv.github.io/mermaid/) diagrams like https://cloose.github.io/CuteMarkEd/ has.
E.g. you write in md
```
   ```mermaid
     graph TD;
          A-->B;
          A-->C;
          B-->D;
          C-->D;
    ```
```
Preview (in fact mermaid) renders diagram.

**Comment by burodepeper** [comment]
Hi @stasberkov,
Thank you for this suggestion. I'll look into adding support for mermaid syntax highlighting in the next release. The rendering of the diagrams however would have to be part of the `markdown-preview` or `markdown-preview-plus` package.

**Comment by nylki** [comment]
> The rendering of the diagrams however would have to be part of the markdown-preview or markdown-preview-plus package.

There is a package for rendering/previewing mermaid diagrams already:
https://atom.io/packages/atom-mermaid

**Comment by burodepeper** [comment]
I've added support for `mermaid` fenced-code-blocks to the dev-branch, but since there's apparently no language pack for it (yet), it is rendered as standard source. @stasberkov Have you considered writing the language pack for mermaid yourself? The syntax doesn't look that difficult.

**Comment by burodepeper** [comment]
I'm closing this because it should be part of `markdown-preview`.
