### ISSUE TITLE
Improve syntax-highlighting compatibility with default syntax-themes

### ISSUE THREAD

**Issue by fusion809** [burodepeper/language-markdown#49]
Hi,

I love this package as it is handy when I am writing posts on my GitHub pages website, but I have noticed that syntax highlighting goes haywire when `<a href="..." target="_blank"></a>` (HTML tag for creating hyperlinks that open in new windows) is included in a markdown document. See this screenshot, for example:
![Highlighting error](http://imgur.com/5lMGXIM.png)
While I realize this error is due to HTML and not markdown, the language that this package is meant to support, I was wondering if I might request this support be added as a feature request. 

Thanks for your time,
Brenton

**Comment by burodepeper** [comment]
Hi Brenton,

Thanks for the issue report. In the bottom right corner, I can see that you have the `Github Markdown` package selected, so _you're not even using this package_ ; ) If you click that and select `Markdown` from the list that pops up, I believe it will sort out your problem.

Let me know if it works.

**Comment by fusion809** [comment]
Rofl, sorry for that. I don't seem to have this package even installed. How do I install this one with apm?  I read the README for this repo, but it didn't really say.

**Comment by fusion809** [comment]
Just run `apm install language-markdown`?

**Comment by burodepeper** [comment]
Yep, that should do the trick.

Note to self: add install instructions to README

**Comment by burodepeper** [comment]
Or install it via the Atom GUI > Settings > Install > Search for language-markdown
That's the path I usually take myself.

**Comment by fusion809** [comment]
OK it works, although, if I can give some honest feedback (I'm honestly not trying to be rude or mean, so please see this as constructive criticism) I've got to say that this package seems to support HTML syntax highlighting better than it does for markdown. Like headings (denoted with hashtags `#`) aren't even highlighted. I'd also like to suggest that you add syntax highlighting for both the link text and the link for links such as `[Sabayon forums](https://forum.sabayon.org/)`. For example, this is how your package highlights this link:

![MD syntax](http://imgur.com/29tITM0.png)

while GitHub Markdown highlights it this way:

![GMD syntax](http://imgur.com/ne32t4z.png).

**Comment by burodepeper** [comment]
Feedback is always good.
The stuff you point out is probably due to your syntax theme. I try as much to follow conventions set by other packages, although that is still a huge blurry area. Give my dark syntax-theme `apm install minimal-syntax-dark` a try and see if you like that better. It supports a lot of small details that other syntax-themes overlook.
Also, could you let me know which theme you are using? I'll see what I can do for better support.

**Comment by fusion809** [comment]
The default theme, "One Dark" (both for UI theme and syntax theme). Kind of funny how when I switched to minimal-syntax-dark theme, HTML syntax highlighting went out the window, but Markdown syntax highlighting became more complete.

**Comment by burodepeper** [comment]
Try reloading Atom.

**Comment by fusion809** [comment]
Reloading? I did restart Atom (i.e., closed it and opened it again) after I installed your theme and before I tried it.

**Comment by burodepeper** [comment]
That's weird. I'm currently in the supermarket, but I'll take a look when I'm back home.

**Comment by fusion809** [comment]
Oh and the issue I started with seems to be affecting this package too with the minimal-syntax-dark-theme. See:

![Minimal-syntax-dark-theme _blank issue](http://imgur.com/7GAmzbA.png)

while it's not as visually obvious with this theme, note how everything is italicized after the `<a href="..." target="_blank">`.

**Comment by burodepeper** [comment]
It still says `Github Markdown` in the bottom right hand corner.

**Comment by fusion809** [comment]
Oh, sorry, rofl. Oh, nvm, you're right the HTML issue is gone too (highlighting is fine with it). Sorry, I switched back to show the issue with the "One Dark" theme before and forgot to switch back.

**Comment by burodepeper** [comment]
No problem.

I'm going to change the title of this issue, and I'll look into how to have the default themes play together better with my package. Let me know if you run into any other issues.

The combo of `language-markdown` with `minimal-syntax-dark` should work fine. If it shows no html highlighting, that could be because you've disabled the default `language-html` package. I've simply included that package, instead of writing my own implementation.

**Comment by burodepeper** [comment]
I've created a new issue (for clarity) to track the progress of compatibility with the default syntax-themes, so I'm closing this one; see #52.
