### ISSUE TITLE
CriticMarkup

### ISSUE THREAD

**Issue by tpoisot** [burodepeper/language-markdown#5]
I can take the lead on this. It's actually simple, here is the code I contributed to `language-gfm`:

~~~ cson
{
    'begin': '{\\+\\+'
    'end': '\\+\\+}'
    'name': 'critic.gfm.addition'
    'captures':
      '0':
        'name': 'critic.gfm.addition.marker'
  }
  {
    'begin': '{--'
    'end': '--}'
    'name': 'critic.gfm.deletion'
    'captures':
      '0':
        'name': 'critic.gfm.deletion.marker'
  }
  {
    'begin': '{=='
    'end': '==}'
    'name': 'critic.gfm.highlight'
    'captures':
      '0':
        'name': 'critic.gfm.highlight.marker'
  }
  {
    'begin': '{>>'
    'end': '<<}'
    'name': 'critic.gfm.comment'
    'captures':
      '0':
        'name': 'critic.gfm.comment.marker'
  }
  {
    'begin': '{~~'
    'end': '~~}'
    'name': 'critic.gfm.substitution'
    'captures':
      '0':
        'name': 'critic.gfm.substitution.marker'
    'patterns': [
      {
        'match': '~>'
        'name': 'critic.gfm.substitution.operator'
      }
    ]
  }
~~~

It would probably be better if it also handled the optional user mentions. I can work on a PR.

**Comment by burodepeper** [comment]
I had already planned to copy your code : )
No need for a PR.

**Comment by tpoisot** [comment]
Cool. So once it's in, I'll add support for the mentions of users. (See [Attribution](http://criticmarkup.com/users-guide.php)).

**Comment by burodepeper** [comment]
Sure, but I won't mind doing it myself. I have a lot of spare time at the moment. Is it okay if I reach out to you when I could use some extra help? We have a private group on slack as well for the more day to day discussions.

**Comment by tpoisot** [comment]
No problem.

**Comment by burodepeper** [comment]
Hey @tpoisot,

I've added your CriticMarkup rules (and tweaked them a little, see https://github.com/burodepeper/language-markdown/blob/master/rules/repositories/critic.cson). I've also added optional emphasis within them. I saw them mentioned somewhere in the specs, so I thought why not.

Could you download the new version (0.0.7) and give them a test run? The scopes are still merely semantic btw, but my [minimal-syntax](https://atom.io/packages/minimal-syntax) theme has debugging styling. Also, you'd have to rename a file to .emdee, or choose the language pack manually.

I'm curious if any of your _proper_ markdown documents work well with my rules. If anything, it will probably be the emphasis that screws up things. I'll be adding tables and code-blocks in the next update.

Thanks.
