### ISSUE TITLE
Pipe symbol subscript in Markdown syntax highlighting wrong

### ISSUE THREAD

**Issue by liamdiprose** [burodepeper/language-markdown#53]
Writing a pipe symbol followed by an underscore, `|_` (for subscript in math-mode) makes the syntax highlighter think any text after is emphasised. The highlighting can be escaped using two underscores, but I don't think this should happen in the first place (unless there is some reason I am not aware of yet).

![atom_markdown_highlighing_error](https://cloud.githubusercontent.com/assets/1769386/11759700/d6ea2b5a-a0e5-11e5-9292-15dfbcf850f3.png)

**Comment by burodepeper** [comment]
Hi @liamdiprose,

I believe you are possibly still using the default `language-gfm` highlighter. Could you check which syntax-highlighter is active? You can see this in the bottom right hand corner. It should say "Markdown". If it says "Github Markdown", you can click it and search for "Markdown" in the window that follows.

If that doesn't fix your problem, could you tell me what other packages you might have installed that could cause a conflict? Below is a screenshot of how your example should be parsed in combination with the `minimal-syntax` theme.

![schermafbeelding 2015-12-12 om 08 03 42](https://cloud.githubusercontent.com/assets/3703530/11760757/7ea2461e-a0a7-11e5-91a0-920be41564f8.png)

**Comment by burodepeper** [comment]
I've just pushed an update that automatically disables `language-gfm`. Let me know if things clear up for you.

**Comment by liamdiprose** [comment]
Yes, that works.

When searching for "Markdown" in the syntax search dialog, it didn't show up. So I installed your package with `apm`, and now its working a charm.

Thank you

**Comment by burodepeper** [comment]
You're welcome. Enjoy!
