### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by tpoisot** [burodepeper/language-markdown#6]
Here is the relevant code I contributed to `language-gfm`

What is missing is that it currently does not parse markdown within the tables (so italics are not rendered as italics).

~~~ cson
{
    'begin': '^\\|'
    'end': '(\\|)?\\s*$'
    'beginCaptures':
      '0':
        'name': 'border.pipe.outer'
    'endCaptures':
      '1':
        'name': 'border.pipe.outer'
    'name': 'table.gfm'
    'patterns': [
      {
        'match': '(:?)(-+)(:?)'
        'captures':
          '1':
            'name': 'border.alignment'
          '2':
            'name': 'border.header'
          '3':
            'name': 'border.alignment'
      }
      {
        'match': '\\|'
        'name': 'border.pipe.inner'
      }
    ]
  }
~~~

**Comment by burodepeper** [comment]
Thanks! I am currently rewriting a lot of stuff (to a better commonmark standard), and I can probably use this as a start for the tables grammar.

**Comment by burodepeper** [comment]
![schermafbeelding 2015-09-23 om 10 52 42](https://cloud.githubusercontent.com/assets/3703530/10041026/632176b2-61e1-11e5-9450-217747edf92d.png)

Work in progress...
