### ISSUE TITLE
after install markdown preview not working

### ISSUE THREAD

**Issue by KaiBueker** [burodepeper/language-markdown#69]
hi,

after install language-markdown the markdown preview doesn't work.
disable package doesn't solve
deinstallation package solve the problem

**Comment by burodepeper** [comment]
Hi @KaiBueker,
This is a known issue, and has to do with `markdown-preview` not recognizing the base scope of documents grammared by `language-markdown`. See #51 for more details, and a temporary workaround. Possibly the updated version of `markdown-preview` is not yet included in Atom. I'll have a look at that.
