### ISSUE TITLE
error in config file

### ISSUE THREAD

**Issue by KaiBueker** [burodepeper/language-markdown#70]
language-markdown disable language-gfm, ok that ist what we want.

but with every opening atom there is a new line in my config file

    disabledPackages: [
      "language-gfm"
      "language-gfm"
      "language-gfm"
    ]

after deinstall language-markdown the problem is solve

**Comment by burodepeper** [comment]
Hi @KaiBueker,
Thanks for the research on this one. That is indeed something I only have to do once ;) Should be an easy fix.

**Comment by burodepeper** [comment]
Fixed, and will be part of the next patch.
