### ISSUE TITLE
Highlight image title with a different color

### ISSUE THREAD

**Issue by vorg** [burodepeper/language-markdown#84]
``` markdown
![](image.jpg "Title Text")
```

ideally would render similar to

<img width="272" alt="screen shot 2016-01-21 at 10 48 22" src="https://cloud.githubusercontent.com/assets/171001/12478431/c644a45e-c02c-11e5-93be-8e8ceea841bc.png">

**Comment by burodepeper** [comment]
Hi @vorg,
That depends on your syntax-theme actually, and I'm currently working on improving compatibility with (generic/default) syntax-themes, see #83. Below are screenshots for how it renders using `minimal-syntax` and `minimal-syntax-dark`.

![schermafbeelding 2016-01-21 om 11 53 11](https://cloud.githubusercontent.com/assets/3703530/12478547/cc24e290-c035-11e5-8023-0ce284b1e7b7.png)

![schermafbeelding 2016-01-21 om 11 53 36](https://cloud.githubusercontent.com/assets/3703530/12478553/d1cc57b4-c035-11e5-9864-07f0e69963b4.png)

**Comment by vorg** [comment]
@burodepeper ah, ok. I'm on Monokai now. Will wait for #83 then.

**Comment by burodepeper** [comment]
How bad is the situation in Monokai?
