### ISSUE TITLE
Syntax highlighting option?

### ISSUE THREAD

**Issue by derekwolfson** [burodepeper/language-markdown#85]
I know this might be a feature and not an issue, but I'd really like it if I could maintain the syntax highlighting from the Github Markdown while using your very useful package.  

Perhaps just an option for those like me?  I just really like my red/orange headings specifically, helps me quickly scan my markdown code.

**Comment by burodepeper** [comment]
Working on it! See #83
What syntax-theme do you use?

**Comment by derekwolfson** [comment]
Damn -- you're good.  I was just about to close the issue when I saw it's already in the works. 

I just started using atom.. so the default theme.  Any suggestions of one jibes well with syntax highlighting at the currently while I wait for #83

**Comment by burodepeper** [comment]
I have two of my own that follow the development over here: minimal-syntax
and minimal-syntax-dark

**Comment by derekwolfson** [comment]
Thanks man... closing this and waiting anxiously for #83.  Killer work.  I love the package.

**Comment by burodepeper** [comment]
Merci beaucoup! :)
