### ISSUE TITLE
Bit too aggressive in matching URLs in non markdown files

### ISSUE THREAD

**Issue by plttn** [burodepeper/language-markdown#87]
```python
def median(list): #https://stackoverflow.com/questions/24101524/finding-median-of-list-in-python
    sortedList = sorted(list)
    listLength = len(list)
    indexMedian = (listLength - 1) // 2

    if (listLength % 2):
        return sortedList[indexMedian]
    else:
        return (sortedList[indexMedian] + sortedList[indexMedian+1]) / 2.0

```
Has the comment matched as `markup.underline.link.https.hyperlink`. Commenting out my style for links in my markdown.less removes the link color, so I think this is this package causing it.

**Comment by burodepeper** [comment]
Hi @plttn,
Thanks for reporting. I'm pretty sure though that `language-markdown` isn't parsing the link (all things parsed by this package have the `md` scope), but it is true that the generic markup style is provided by 'me'. I believe the hyperlink detection is done by the package `language-hyperlink` that comes default with Atom, see: https://atom.io/packages/language-hyperlink
I'm closing this issue as irrelevant to this package.

**Comment by plttn** [comment]
Thanks, that got me looking in the right place on where i needed to adjust some styles in my theme to get it to work the way I wanted.
