### ISSUE TITLE
language-markdown blocks markdown-preview

### ISSUE THREAD

**Issue by popas90** [burodepeper/language-markdown#96]
I cannot preview my document when language-markdown is enabled, either from the keybinding or from the Packages menu. Nothing happens when I activate the option.

If I deactivate language-markdown and reload Atom, then I can preview again.

I'm using the core package (markdown-preview).

**Comment by burodepeper** [comment]
Hi @popas90,

I have a few question that might narrow down this issue:
- With `language-markdown` enabled, is the option `Markdown Preview` available when you right-click the file (in the tree-view) you want to preview?
- Are you using any other packages?
- With the `keybinding-resolver` core package enabled (press <kbd>cmd + period</kbd> to enable the pane), does the `markdown-preview:toggle` option show up when you use the keybinding?
- Are you using Atom in `dev-mode`?
- (and just to be sure) Are you using the latest version of Atom and of `language-markdown`?

**Comment by popas90** [comment]
> With language-markdown enabled, is the option Markdown Preview available when you right-click the file (in the tree-view) you want to preview?

Yes, it's enabled and it's working fine.

> Are you using any other packages?

Yes, lots :)

> With the keybinding-resolver core package enabled (press cmd + period to enable the pane), does the markdown-preview:toggle option show up when you use the keybinding?

Yes, it's correctly assigned to Ctrl+Shift+M

> Are you using Atom in dev-mode?

No.

> (and just to be sure) Are you using the latest version of Atom and of language-markdown?

Atom v1.019, just installed language-markdown today

**Comment by burodepeper** [comment]
Thanks!

So, to narrow the issue down, is the following correct:

| action | success
| --- | ---
| preview via right-click in tree-view | works
| preview via keybinding | doesn't work
| preview via command palette | doesn't work

**Comment by popas90** [comment]
Yes, that's correct. Thank you!

**Comment by burodepeper** [comment]
Okay, thanks. Well, at least you can use the preview via right-click for the time being. Oh, argh, silly of me, could you update Atom? ; ) For some reason I skimmed over the version number you mentioned, but Atom is currently at v1.6 (and has a newer version of markdown-preview included), and I believe this issue been fixed since v1.4. For more info, see #51. Let me know if you still experience this issue after updating.

**Comment by popas90** [comment]
You're right, i updated and now it's fixed. My bad, i thought Atom got updated via the linux package manager, so i assumed it was (close to) the latest.

**Comment by burodepeper** [comment]
Good to know that it is fixed now! Fyi, whenever a new Atom version is released, an icon (resembling a squirrel if I recall correctly) appears in the bottom right-hand corner of the window. No idea why this rather critical element is so tactfully hidden...
